In [3]:
import requests
from bs4 import BeautifulSoup
import lxml

In [4]:
url=("https://www.slpa.lk/port-colombo-list/news")
response=requests.get(url)
soup=BeautifulSoup(response.content, "lxml")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <!-- Mirrored from designarc.in/logis-cargo/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Mar 2016 02:46:54 GMT -->
 <head>
  <meta charset="utf-8"/>
  <title>
   Sri Lanka Ports Authority - News
  </title>
  <!-- viewport meta -->
  <link href="https://www.slpa.lk//favicon.ico" rel="icon" type="image/x-icon"/>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" name="viewport"/>
  <!--[if lte IE 9]>
    <h1 style="background-color: yellow; color: red;">You are using a version of IE less than IE9, Please Upgrade Browser</h1>
    <![endif]-->
  <script type="text/javascript">
   var js_base_url = "https://www.slpa.lk/";
        var js_site_url = "https://www.slpa.lk/";

        //alert(js_url_path);
  </script>
  <!-- Matomo -->
  <script>
   var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//mpma.slpa.lk/matomo/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
  </script>
  <!-- End Matomo Code -->
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-73651247-1', 'auto');
        ga('send', 'pageview');
  </script>
  <!-- styles -->
  <!-- helpers -->
  <!-- <link rel="stylesheet" href="application_resources/javascripts/plugins/bootstrap/css/bootstrap.min.css"> -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet"/>
  <!-- fontawesome css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
  <!-- strock gap icons -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/Stroke-Gap-Icons-Webfont/style.css" rel="stylesheet"/>
  <!-- revolution slider css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/revolution/css/settings.css" rel="stylesheet"/>
  <!-- flaticon css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/flaticon/flaticon.css" rel="stylesheet"/>
  <!-- jQuery ui css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet"/>
  <!-- owl carousel css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.carousel.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.theme.default.min.css" rel="stylesheet"/>
  <!-- animate css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/animate.min.css" rel="stylesheet"/>
  <!-- fancybox -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/fancyapps-fancyBox/source/jquery.fancybox.css" rel="stylesheet"/>
  <!-- master stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/style.css" rel="stylesheet"/>
  <!-- responsive stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/responsive.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/stylesheets/magnific-popup.css" rel="stylesheet" type="text/css"/>
  <!-- jQuery js -->
  <!-- <script src="application_resources/javascripts/plugins/jquery/jquery-1.11.3.min.js"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
  </script>
 </head>
 <body onload="xxx()">
  <script>
   function xxx(){
//alert("test");
}
  </script>
  <!-- Start header -->
  <header class="stricky" id="header">
   <div class="thm-container clearfix">
    <div class="logo pull-left">
     <a href="https://www.slpa.lk/">
      <img alt="" src="https://www.slpa.lk/application_resources/images/logo_1.png"/>
     </a>
    </div>
    <div class="header-info pull-right">
     <div class="info-box">
     </div>
     <div class="info-box">
      <div class="icon-box no-border">
       <i class="icon icon-FileBox">
       </i>
       <center>
        <a href="tel:1984">
         <img alt="" height="60" src="https://www.slpa.lk/application_resources/images/tel-1984.png"/>
        </a>
       </center>
      </div>
      <div class="text-box">
       <p class="highlighted">
        E-Mail : info@slpa.lk
       </p>
       <p>
        Fax : 	+94-11 2440651
       </p>
       <p class="highlighted">
        Call Us : +94-11 242 12 01
       </p>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=si&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Sinhala
       </a>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=ta&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Tamil
       </a>
      </div>
     </div>
     <div class="info-box search-box-wrapper">
      <br/>
      <div class="text-box">
      </div>
     </div>
    </div>
   </div>
  </header>
  <!-- End header  -->
  <!-- Start mainmenu -->
  <nav class="main-menu-wrapper stricky">
   <div class="thm-container menu-gradient">
    <div class="clearfix">
     <div class="nav-holder pull-left">
      <div class="nav-header">
       <button>
        <i class="fa fa-bars">
        </i>
       </button>
      </div>
      <div class="nav-footer">
       <ul class="nav notranslate">
        <li>
         <a href="https://www.slpa.lk/">
          Home
         </a>
        </li>
        <li class="has-submenu">
         <a>
          About
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/slpa">
            SLPA
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vision-and-mission">
            Vision &amp; Mission
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/board-of-directors">
            Board Of Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/act">
            ACT
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/procedures">
            Procedures
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/circulars">
            Circulars
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/awards">
            Awards
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/annual-reports">
            Annual Reports
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tariff">
            Tariff
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/right-to-information">
            Right To Information
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/publications">
            Publications
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Ports
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/colombo">
            Colombo
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/galle">
            Galle
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/trincomalee">
            Trincomalee
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/hip">
            HIP
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/oluvil">
            Oluvil
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/kankesanthurai">
            Kankesanthurai
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          E-Systems
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ber">
            Berthing Programme
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tms-esystem">
            TMS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/import">
            Import
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/export">
            Export
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/ro-ro">
            RO-RO
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/bulk-and-break-bulk">
            Bulk &amp; Break Bulk
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/fcl-cutoff-info">
            FCL Cutoff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/destuff-info">
            Destuff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/empty-containers">
            Empty Containers
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/online-entry-permits">
            Online Entry Permits
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vessels-in-port">
            Vessels In Port
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://hris.slpa.lk/login" target="_blank">
            HRIS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/clearing-passes">
            Clearing Passes
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/bungalow/index.php" target="_blank">
            Bungalow Booking
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://esys.slpa.lk/b/port-tours/" target="_blank">
            Port Tours
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Projects
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/projects">
            Projects
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Procurement
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/contacts-general-info">
            Contacts - General Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/foreign-purchases">
            Foreign-Purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/local-purchases">
            Local purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/other">
            Other
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Contacts
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ministry">
            Ministry
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/chairman-directors">
            Chairman &amp; Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/management-team">
            Management Team
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/mahapola">
            Mahapola Academy
           </a>

In [56]:
#Latest News

news=soup.find_all("div",class_="content")
print(news)

[]

In [6]:
headers=[]

for i in news:
   headers.append(i.select_one("h3").get_text(strip=True))
print(headers)

['CMA CGM Senior Executives Visit the Port of Colombo', 'U.S. Assistant Secretary of State S. Paul Kapur Visits the Port of Colombo', 'SCO Delegation Visits Port of Colombo and Pilot Station', 'Maersk Engages with SLPA on Enhancing Terminal Productivity in Colombo', 'SLPA Signs Terminal Service Agreement with Unifeeder Lanka to Strengthen Operational Efficiency', 'CMA CGM Delegation Holds Discussions with Sri Lanka Ports Authority on Strengthening Cooperation', 'German Ambassador Visits SLPA to Discuss Port Development Opportunities', 'ADB President Masato Kanda Leads Delegation on Site Visit to Port of Colombo', 'SLPA Chairman Reviews Port of Colombo Operations Amid Middle East Tensions', 'DR. PARAKRAMA DISSANAYAKE ASSUMES DUTIES AS CHAIRMAN SLPA', 'Third Berth at Colombo East Container Terminal Enters Service, Marking a New Phase of Operational Scale', 'Colombo East Container Terminal Receives Maiden Call of Ever Eon', 'Sri Lanka and Maersk Explore Expansion Opportunities at Davos Meeting', 'SLPA Holds Discussions with COSCO Shipping', 'Ultra-Heavy Cargo Handled at Port of Colombo', 'SLPA, CMA?CGM Ink Terminal Service Agreement to Strengthen Colombo Port', 'Port of Colombo Records Historic High of 8.29 Million TEUs in 2025', 'SLPA and Maersk Deepen Operational Coordination at Port of Colombo', 'SLPA and Evergreen Strengthen Strategic Partnership', 'MSC and SLPA Sign New Terminal Service Agreement', 'Hapag-Lloyd Delegation Visits Sri Lanka Ports Authority', 'SLPA Launches Second Berth at Colombo East Container Terminal', 'Port of Antwerp-Bruges Delegation Strengthens Maritime Ties with Sri Lanka', 'SLPA Hosts Successful Port Visit for CILT International Convention', 'Strengthening Legal Foundations for Sri LankaŌĆÖs Ports and PPPs with U.S. Support', 'U.S. Congressional Delegation Meets Sri Lanka Ports Authority Management.', 'Maersk Line Strengthens Ties with SLPA Terminals', 'Gateways to Growth: US, Sri Lanka, and Maldives Forge Stronger Maritime and Trade Partnerships', 'CELEBRATING 46 YEARS OF EXCELLENCE: SRI LANKA PORTS AUTHORITY', 'Sri Lanka Ports Authority delegation visits Port of Antwerp-Bruges to advance cooperation', 'Japanese Business Delegation Engages with SLPA on Colombo Port Development', 'Sri Lanka Ports Authority Welcomes MSC MARIELLA ŌĆō The Largest Container Vessel Ever to Call at Sri Lanka', 'Hapag-Lloyd Senior Delegation Meets with Sri Lanka Ports Authority Leadership', 'Newly Appointed Japanese Ambassador Visits Port of Colombo', 'JICA Delegation Visits Colombo Port', 'SLPA Terminals JCT & ECT achieves the 2.4Mn TEUs amidst competitive environment while Port of Colombo achieves Record Growth in 2024, Setting the Stage for Future Expansion', 'ŌĆ£We have entered an era where  we must work together for the success of the countryŌĆØ  - Admiral Sirimevan Ranasinghe Rtd., Chairman, Sri Lanka Ports Authority', 'MV. Navios Unite marks maiden call at JCT SLPA', 'SLPA Terminals Record All-Time High of 2.41 Million TEUs in 2024 Amidst Competition', 'ŌĆ£The optimum usage of energy is a mandatory requirementŌĆØ ŌĆō Eng. Ganaka Hemachandra, Managing Director, SLPA', 'Minister Bimal Rathnayake Assumes Duties, Vows to Combat Corruption and Promote Unity', 'Port of Colombo Hosts Joint CBRNE Exercise', 'Colombo Plan Officials meet Port and Aviation Ministry officials to strengthen partnership', 'Admiral Sirimevan Sarathchandra Ranasinghe (Rtd), new Chairman of Sri Lanka Ports Authority', 'SeaLead Launches New Liner Service with Sri Lanka Ports Authority', 'Steering Towards a Safer Future: World Maritime Day 2024', 'Vijitha Herath Assumes Office as Minister of Ports and Civil Aviation, Calls for Integrity and Unity in Governance', 'MV EVER ARM makes first call at the SLPA controlled Colombo East Container Terminal', 'Port of Colombo Welcomes EVER ARM: A Milestone for South AsiaŌĆÖs Busiest Port', 'British High Commissioner Pays Courteous Visit to Port of Colombo', 'Clarifying Media Misrepresentation on Port Operations', "ŌĆ£With ongoing developments we are confident in the Port of Colombo's evolution as the hub of South AsiaŌĆØ       -  Keith D. Bernard, Chairman SLPA", 'Incident at Jaya Container Terminal: Fire Averted on MV ŌĆ£MSC CAPETOWN IIIŌĆØ', 'SLPA Marks 45 Years with Celebrations and Developments', 'SLPAŌĆÖs 45 Years of Excellence', 'Port of Colombo Becomes WorldŌĆÖs Top Performer in Growth', 'NDC Course Participants Visit Port of Colombo', 'SLPA Officials Visit Virginia Port:  Insights on Cutting-Edge Technology and Sustainable Operations', 'Charting Sustainable Ports: U.S. Embassy Event at Indo-Pacific Business Forum', 'SLPA officials meet World Bank  Special Team and International Finance Corporation officials', 'East Container Terminal Welcomes Three New STS Cranes', 'Japanese Minister for Foreign Affairs - Hon.Yoko Kamikawa visits Port of Colombo', 'SLPA container volumes expand 48% YoY in 1Q24', 'Port of Tianjin China expresses willingness to assist transforming Colombo Port', 'STS Cranes Shifted to JCT Phase V', 'MV MAERSK EdmontonŌĆÖs First Call at ECT of SLPA', 'X-Press Feeders wins top accolade at Colombo Ports Awards', 'Colombo Port transshipment growth surges for third month', 'SLPA collaborates with JCT, SAGT and CICT, hosts Port of Colombo Awards Night', 'M.V. Ane M├”rsk Makes Maiden Port Call in Colombo, Leading the Charge in Sustainable Shipping', 'SLPA gets brand new cranes worth $ 282 m to boost capacity at East Container terminal', "U.S. Backs Expansion of Sri Lanka's Ports Sector with Capacity Building Program for Sri Lanka Ports Authority (SLPA)", 'ŌĆ£Colombo PortŌĆÖs Bandaranaike quay to convert into a passenger terminalŌĆØ', 'Aitken Spence Travels welcomes 3 cruises in a single day to Colombo port', 'Marella Discovery 2 cruise liner calls on Colombo', 'Luxury passenger vessel RESELIENT LADY carrying 2318 passengers and 1194 crew on board calls the Port of Colombo', 'Cruise vessel Aida Bella to call Port of Colombo', 'SL mulls investment for green hydrogen & ammonia production', 'ŌĆ£SLPA to transform Colombo Port into eco-friendly facility by 2030ŌĆØ', 'Sri Lanka-India passenger ferry services resume after 40 years', 'SLPA targets Rs. 35 Bn profit in 2023', 'SLPA poised as an exemplary model for SOEs, says its Chairman', 'Sri Lanka Ports Authority ŌĆō Enquiry Center', 'Port Community System a must ŌĆō Minister', 'Talaimannar pier to be re-constructed after 37 years at a cost of Rs.1.8bn', 'Maritime Facilitation Centre Marks Milestone in Sri LankaŌĆÖs Infrastructure Development', 'Port of Colombo: Foundation Stone Laid for ECTŌĆÖs Operation & Admin Building', 'Celebrating 44 Years of Excellence: Sri Lanka Ports Authority', 'ConnectX by SLPA: Official Trailer', 'A high profile delegation from the Port of Colombo attends business promotions visit at VOC Port Authority, Tuticorin, India', 'KKS Port opens with MS Empress luxury vessel calling over from Chennai', 'MV Empress: Trincomalee Welcomes Cordelia CruisesŌĆÖ Magnificent Cruise Ship', 'SLPA Chairman and Indian High Commissioner Discuss Maritime Collaboration in Colombo', 'Minister Explores Investment Opportunities at Port of Colombo during Successful Singapore Visit', 'Sri Lanka Ports Authority Announces Appointment of new Managing Director', 'Ambassador for France visits Port of Colombo', '30 Year Development Plan of the North Port of Colombo', '30 Year Development Plan of the North Port of Colombo', 'U.S Department of Transportation officials meet SLPA Chairman', 'VIKING NEPTUNE CALLS AT THE PORT OF COLOMBO', 'Port of Trincomalee Commences night operations', 'The first vessel under port promotions programme calls at the East Container Terminal', 'Japanese State Minister of Foreign affairs Visits Port of Colombo', 'Phoenix Reisen calls on Colombo with 500 passengers', 'Lanka can become maritime hub in the region - CASA', 'Sri Lanka Ports Authority commences work in 2023', 'Port dredgers ŌĆśDiyakowullaŌĆÖ and ŌĆśHansakawaŌĆÖ resume work with MinisterŌĆÖs intervention', 'Minister instructs expedite stalled construction work at the Jaya Terminal', 'ILO, Japan partner to enhance economic wellbeing of returnee and aspirant Sri Lankan migrant workers', 'SLPA donates to the Consolidated Fund of the Government', 'ŌĆ£Ocean OdysseyŌĆØ super luxury passenger ship arrives in Colombo port', 'Colombo Port: Highest Performing Port in South Asia ŌĆō UNCTAD', 'Mein Schiff 5 arrives in Port of Colombo', 'A high profile delegation from Port of Colombo visits Bangladesh', 'Norwegian luxury cruiser ŌĆśViking MarsŌĆÖ anchors in Colombo', 'Industrial Peace vital to make Sri Lanka, a Maritime Hub in Indian Ocean ŌĆō Minister', 'SLPA Chairman meets Bangladesh High Commissioner', 'Colombo Port: Work on Colombo West International Terminal begins', 'Colombo Dockyard Launches the ŌĆ£Sophie GermainŌĆØ', 'Second Batch of Ilmenite Exports from Trinco', 'OPV P627 arrives at Port of Colombo', 'Minister inspects the ECT Project', 'Australian Navy ships arrive at the Port of Colombo', 'New SLPA Chairman Assumes Duty', 'KOICA Delegates Visit SLPA', 'Colombo Port Wins 2022 GPF Top Awards', 'Hapag-Lloyd introduces new feeder service between Colombo and Chittagong', 'World Maritime Day ŌĆö History and Significance', 'Sri Lanka: Ports as a Premier Bunker Oil Supplier', 'Minister Visits Galle Port', 'CASA Conducts 56th AGM', 'Two deep water terminals to be added soon', 'ONE launches new feeder service via Colombo', 'Thirty five SLPA employees receive Port Management Diplomas', 'Shipping industry to remove the Indian Ocean High Risk Area', 'CH Clare carrying 21,000 t of fertilizer arrives', 'Tug-boat fleet to boost SLPA efficiency ŌĆō Minister', 'SLPA: Three New Reach Stackers to Improve Operational Efficiency', 'Sri Lanka Ports Authority Celebrates 43rd Anniversary', 'New World Maritime Theme highlights environmental legacy', 'Training opens new horizons for women in ports', 'Bangladesh High Commissioner Pays Courtesy call on the Minister', 'Enhancing shipping connectivity between Chattogram and Colombo Ports', 'VIDEO: Chairman Pays a Progress Inspection Visit of East Container Terminal', 'ŌĆ£Adequate fuel reserves available ŌĆō No disruption to port operationsŌĆØ', 'My Goal Is to Increase Port Revenue up to $ 1 Billion ŌĆō SLPA Chairman', 'Japanese Ambassador Pays Courtesy call on the Minister', 'Enhance International Confidence in Ports ŌĆō President', 'Shipping Agents Reaffirm Continuity of Export-Import Business', 'Colombo the most efficient port in South Asia ŌĆō World Bank and S&P', 'SLPA refutes erroneous claims', 'Port of Colombo: Operators Rebuff Fabricated News', 'SLPA: Dedicated WhatsApp number introduces to curb fraudulence', 'CASA donates 100 bicycles to achieve Green Port objectives', 'Colombo Dockyard launches ŌĆ£Misje VitaŌĆØ, 5000DWT EcoBulk carrier being built for Misje Eco Bulk AS', 'Colombo Port terminal operators reassure global customers', 'INTERVIEW: Let us work beyond the proverbial box and take the industry to greater heights', 'Port of Colombo: CASA Commends the Commitment of SLPA and other Terminal Operators', 'SLPA: Port Services and Operations Continue Without Hindrance', 'Port Operations are Normal ŌĆō SLPA', 'Minister instructs to encourage shipping lines to pay SLPA in USD', 'Port of Colombo: Status Report', 'ŌĆ£Everything is Smoothly Going on,ŌĆÖ SLPA Chairman told the CNBC', 'Do not be misled by Fake News: On Video Circulating about JCT Operation', 'Sri Lanka Ports Authority wins the GPF Awards', 'US Undersecretary Victoria Nuland Visits Port of Colombo', 'Two posts established  for SLPA  and Ministry of Ports and Shipping  to look into  Employee Grievances', 'SLPA Launches a New Documentary Series on Global Ports', 'SLPA: Tracking the Impressive Achievements in Ports and Shipping', 'MV HR SARERA becomes first inaugural caller at the JCT after Covid-19 pandemic', '24 Seafarers trained at the Mahapola Ports & Maritime Academy (MPMA) of SLPA pass out', 'Removal of the wreck of X-Press Pearl begins', 'Bangladesh High Commissioner Pays Courtesy call on SLPA Chairman', 'President instructs release of essential items containers', 'Galle Port Development Symposium 2022: Message from the Minister', 'Galle Port Development Symposium 2022: Message from the Chairman', 'SLPA Chairman assumes duties', 'President flags off second phase of ECT', 'The Construction of the second phase of the Eastern  Terminal begins', 'Sri Lanka Ports Authority commences 2022', 'The Port of Colombo will handle over 24 million TEUs by 2040', 'Port of Colombo is the Best Connected-port in South Asia ŌĆō UNCTAD', 'SLPA Begins Booster Dose Roll-Out Against COVID-19', 'Port of Colombo is the Best Connected-port in South Asia ŌĆō UNCTAD', 'Colombo Dockyard Opens a Branch in Trincomalee', 'CHAIRMAN SLPA VISITS CASA OFFICE', 'Request for Expression of Interest (EOI)', 'WorldŌĆÖs largest container ship in Colombo', 'VIDEO: SLPA warmly welcomes Eve Ace', 'VIDEO: We are open for development ŌĆō SLPA Chairman', 'SLPA Acts timely to discharge leaky container onboard MV Thalassa Patris', 'WorldŌĆÖs biggest container ship Ever Ace to call at Colombo Port tomorrow', 'SLPA Signs the Agreement for The Largest Investment Ever In Port Sector of Sri Lanka', 'Steps have been taken to minimize the ITT delay at the Port of Colombo', 'Sri Lanka Ports Authority establishes the First Ever  Intermediate Covid Treatment Centre', 'Sri Lanka Ports Authority Celebrates 42nd Anniversary', 'SRI LANKAŌĆÖS HARBOUR DEVELOPMENT', 'SLPA Successfully Reworks Leaked Chemical Container On board', 'SLPA with ILO support commences training for seafarers', 'ECT: Bid evaluation for civil works, equipment begins', 'A greater synergy between India and Sri Lanka pivotal to handle future container volume growth ŌĆō SLPA Chairman', 'SLPA holds meeting with CASA', 'Bangladesh Support for Shipping Industry in Sri Lanka is vital ŌĆō SLPA Chairman', 'SLPA Chairman visits CICT and SAGT', 'Upul Jayatissa Appointed MD of SLPA', 'SLPA new chairman boosts employeesŌĆÖ morale for more dynamic performance', 'SLPA Chairman assumes duties', 'Capt. Keppetipola Appointed Chairman of SLPA', 'SLPA launches video series on Port of Colombo', 'X-Press Pearl Fire: Views on national misfortunes should be in good faith ŌĆō Minister', 'X-Press Pearl Fire: For the first time in decades, Port operations halt due to adverse weather for 39 hours ŌĆō Chairman SLPA', 'X-Press Pearl Fire: Fragile freights and dangerous cargo ŌĆō nature of the shipping industry ŌĆō VC SLPA', 'X-Press Pearl Fire: Harbour Master sets the record straight', 'Minister of Ports and Shipping, Chairman SLPA   join in inspecting MV X-Press Pearl', 'SLPA to Continue Port Services During the Upcoming Holidays ŌĆō Chairman', 'SLPA douses the fire on X-Press Pearl', 'My goal is to develop our employees ŌĆō SLPA Chairman', 'Colombo Port to offer thousand beds for Covid-19 patients', 'SLPA Upgrades its Terminal Management System', 'Special Notice - Finance Division Activities', 'Colombo Port is the top-ranked port in South Asia ŌĆō CPPI', 'SLPA begins inoculating employees with second dose of COVID-19 vaccine', 'Operations in the port and shipping sector continue with no interruptions', 'World Day for Safety and Health at Work', 'CPAC meets to review current state of Covid-19', 'Sri Lanka Ports Authority celebrates Sinhala-Tamil New Year', 'Sri Lanka Ports Authority launches ŌĆśTheerthaŌĆÖ Magazine', 'SLPA Celebrates International WomenŌĆÖs Day', 'CHEC donates a PCR machine for Sri Lanka Ports Authority', 'Every organization needs visionary leadership for success ŌĆō SLPA Chairman', 'A new pilot boat for the Sri Lanka Ports Authority', 'SLPA initiates Covid-19 vaccination', 'President inspects the construction of the model stalls', 'SLPA Female Gantry Crane Operators Receive Excellence Award', 'SLPA implements clearance through electronic methods', 'SLPA Launches new Edition of the Covid-19 Prevention Guideline', 'SLPA  Employees and Military Ranks of SL Army  who shouldered the responsibility of protecting the reputation of Sri Lanka Ports Authority commended.', 'Port of Colombo Operations ŌĆō Status Report', 'SLPA lays foundation stone for a new Container Freight Station', 'SLPAŌĆÖs Covid-19 Preventive Mechanism is Commendable ŌĆō Quarantine Unit', 'We wish you a very Happy New Year ŌĆō SLPA', 'Sri Lanka Ports Authority declared an essential service', 'Port of Colombo: Returns to normalcy', 'Port of Colombo Operation Update', 'Rapid Antigen Tests for Randomly Selected Groups Continue', 'SLPA Chairman meets with Army Commander to discuss COVID-19 Control Measures', 'SLPA commences Phase V of JCT', 'All Operations Return to Normal', 'SLPA perform its duties duly in distribution of imported fertilizer', 'SLPA: Port operations continue ŌĆō Minister inspects the situation', 'Sri Lanka Ports Authority declared as an ŌĆśessential serviceŌĆÖ', 'Our commitments lead us to overcome any challenge', 'Colombo Port ranked as worldŌĆÖs 18th best-connected port', 'We all have a responsibility to ensure import and export', 'SLPA: Police officer appoints to coordinate port activities', 'Do not violate the quarantine laws ŌĆō SLPA', 'Bulk carriers with fertilizers arrive at Port of Colombo', 'PCR tests carried out on another 200 at the Colombo Port', 'New Chairman and Managing Director of SLPMCS assume duties', 'Colombo Port Operations Continue Without Any Hindrance', 'East Container Terminal Inaugurates for Operations', 'Cargills Foodcity opens its branch in Colombo Port', 'Behind The Enemy Lines: Fighting the Unseen Virus ( An Interview)', 'All activities of Mahapola Academy carried out under health instructions', 'No one in SLPA infects with Covid19 ŌĆō Chairman', 'DECLARATION FORM TO BE FILLED WHEN ENTERING PORT PREMISES', 'Fresh random samples of 225 employees and port users test negative for Covid-19', 'State Minister on a special visit at the Port of Colombo', 'SAGT celebrates 21 years of maritime excellence', 'Sri Lankan Govt to expand Galle, Trinco, KKS Ports for regional, global exports', 'EDB and DCS collaborate to capture logistics sector data', 'Hon. Minister of Ports and Shipping Rohitha Abeygunawardena on a special port inspection visit at the Port of Colombo', 'Sri Lanka to become South AsiaŌĆÖs LNG Hub:  Floating storage trading facility in HŌĆÖtota from Pearl Energy', 'New Secretary to the Ministry of Ports and Shipping assumes duties', 'New MSC shipping service to Colombo', 'Hon.Minister of Ports and Shipping Rohitha Abeygunawardena assumes duties', 'Sri Lanka Ports Authority celebrates 41st Anniversary', 'SLPA assures safe handling of dangerous cargo under UN regulations', 'SLPA contributes Rs. 18.6 million to PresidentŌĆÖs Covid19 Relief Fund', 'Sri Lanka Ports Authority signs agreement with SLT', 'Mahapola Ports & Maritime Academy to resume training programmes', 'President floats committee on JCT and ECT', 'Seafarers are the forerunners of maritime industry', 'Our commitment to onboard training excellence: The legacy will continue', 'Euro Spirit Arrives Colombo Port', 'Mahapola Maritime Academy and Rakna Lanka sign MoU to boost maritime education', 'Sri Lanka wins new business providing services to Cruise Ships anchored outside Colombo Port', 'No One in Colombo Port Infected with Covid-19: PCR & Antibody Tests Confirmed', 'Employees and Port users of Colombo Port undergo PCR tests', 'Cruise shipŌĆÖs crew arrived at Colombo Port sends home country safely', 'SLPA Guideline for Eradicating Covid-19', 'SLPA: Operational Strategies during Covid19', 'SLPA launches the Guideline for Eradicating Covid-19 Pandemic', 'New Nursing Quarters for the IDH hospital opened', 'New procedure for MCC and LCL delivery of cargo to ease delay during Covid-19', 'DonŌĆÖt be misled by fake news: Port operations are continuing ŌĆō SLPA', 'Response from Sri Lanka Ports Authority to fake news', 'Covid-19 restrictions are no obstacles to release vehicles imported at the Port ŌĆō Sri Lanka Ports Authority

In [7]:
content=[]

for item in news:
    content.append(item.select_one("p").get_text(strip=True))
print(content)

['Mr Jesper Stenbak, Senior Vice President ADRO of CMA CGM, and Ms Christine Cabau, Executive Vice President of CMA CGM, accompanied by Mr Eric Daniel Van Den Driesen, Country General Manager of CMA CGM Lanka (Pvt) Ltd, and Mr Pasan Periyapperuma, Deputy General Manager – Operations and LogisRead More', 'The Sri Lanka Ports Authority welcomed S. Paul Kapur to the Port of Colombo yesterday, in the presence of SLPA Chairman Dr. Parakrama Dissanayake. Mr Kapur, who leads the United States’ diplomatic engagement with South and Central Asia as the Assistant Secretary of State, visited the Port oRead More', 'The Secretary-General of the Shanghai Cooperation Organization (SCO), Mr. Nurlan Yermekbayev, currently undertaking an official visit to Sri Lanka, today visited the Port of Colombo, where he was received by senior officials of the Sri Lanka Ports Authority and relevant government representativesRead More', 'Delegates from Maersk met with senior officials of the Sri Lanka Ports Authority today at the SLPA Headquarters, Port of Colombo, to discuss operational performance and future collaboration relating to Maersk vessel and terminal activities in Colombo.\n\nThe Maersk delegation included Mr Karan TariRead More', 'The Sri Lanka Ports Authority and Unifeeder Lanka (Pvt) Ltd have entered into a Terminal Service Agreement valid until 2028, setting out defined terms for terminal services at the Port of Colombo.\n\nThe signing was attended by Dr. Parakrama Dissanayake (Chairman), Eng. Herath M. P. Jayawardhana (VRead More', 'A delegation from CMA CGM visited the Sri Lanka Ports Authority and held discussions with the Chairman, Dr. Parakrama Dissanayake, along with members of the Authority’s senior management.\n\nThe CMA CGM delegation included Colin Gout, Vice President – Procurement, Ports and Terminal, anRead More', 'Dr. Felix Neumann, Ambassador of Germany to Sri Lanka and the Maldives, paid an official visit to the Sri Lanka Ports Authority (SLPA), where he met with Chairman Dr. Parakrama Dissanayake together with members of the Authority’s senior management.\n\nDuring the meeting, discussions were heldRead More', 'The Asian Development Bank (ADB) delegation, led by President Mr. Masato Kanda, visited the Sri Lanka Ports Authority, including the Port of Colombo and the pilot station, to review ongoing development projects and operational activities.\n\nThe team, including Mr. Mahinda Siriwardana, Ms. Sona ShrRead More', 'SLPA Chairman Dr. Parakrama Dissanayake chairs a meeting with SLPA officials, terminal operators, and representatives of shipping lines to review Port of Colombo operations\n\n\n\nConvenes discussion with stakeholders from port officials to terminal operators and representatives of global shipping linesRead More', 'Distinguished maritime, logistics and corporate leader and the Advisor to the President on Maritime, Ports and Logistics, Dr.Parakrama Dissanayake assumed duties as the Chairman of Sri Lanka Ports Authority (SLPA) on February 17, 2026.\n\nThe appointment letter was handed over by the Minister of PoRead More', 'Expanded quay length and carrier confidence signal accelerated growth for the Port of Colombo’s transhipment operations\n\n\xa0\n\nThe Colombo East Container Terminal of the Sri Lanka Ports Authority marked a pivotal operational milestone today with the commissioning of its third berth at the PoRead More', 'Newly delivered Post-Suezmax vessel highlights SLPA’s deep-water capacity and modern terminal infrastructure\n\nEVER EON, a newly delivered Post-Suezmax class container vessel, made its maiden call at the Colombo East Container Terminal (ECT) of the Sri Lanka Ports Authority on 22 January 2026,Read More', 'Prime Minister and A.P. Moller–Maersk Chairman discuss policy certainty, private-sector alignment and the Port of Colombo’s growing trade role\n\nPrime Minister Dr Harini Amarasuriya met Mr Robert M. Uggla, Chairman of A.P. Moller – Maersk on 21 January at the World Economic Forum inRead More', 'The Sri Lanka Ports Authority (SLPA) recently held discussions with representatives of COSCO Shipping as part of its ongoing engagement with major global shipping lines. The meeting was aimed at strengthening operational coordination and service alignment at the Port of Colombo, and reaffirmed thRead More', 'The Port of Colombo successfully berthed MV Rudolf on Tuesday, 13 January 2026, handling an ultra-heavy project cargo shipment for the Melwa Cement Ball Mill Project.\n\nThe vessel carried 533 packages with a total weight of 1,725 MT and a volume of 4,600 CBM, including individual units weighing upRead More', 'SLPA Terminals and CMAŌĆ»CGM recently signed a Terminal Service Agreement aimed at enhancing business collaboration and attracting greater container volumes to the Port of Colombo. The signing ceremony was attended by senior officials from both organisations, including Admiral Sirimewan Ranasinghe (Read More', 'The Port of Colombo reached a defining point in 2025 by recording a throughput of 8,291,178 TEUs, the highest volume ever handled in its history. This result follows a strong performance in 2024, when the port processed 7,792,069 TEUs, and affirms Colombo’s standing as the leading containerRead More', 'The Sri Lanka Ports Authority (SLPA) continued its engagement with leading global shipping partners this week, hosting senior representatives from A.P. Moller – Maersk’s Dubai Regional Hub as part of ongoing efforts to strengthen collaboration and operational alignment at the Port ofRead More', 'The Sri Lanka Ports Authority (SLPA) and Evergreen Shipping Line further strengthened their long-standing partnership during a productive meeting between senior leadership teams recently at the Sri Lanka Ports Authority. Evergreen Shipping Agency Lanka (Pvt) Ltd. was represented by Vice PresidentRead More', 'MSC, the world’s largest container line and the highest-volume carrier at the Port of Colombo, confirmed a renewed commitment to its operations in Sri Lanka today. Mediterranean Shipping Company (MSC) and the Sri Lanka Ports Authority have signed a new Terminal Service Agreement that will gRead More', 'A senior delegation from Hapag-Lloyd recently visited the Sri Lanka Ports Authority (SLPA) to strengthen ties and explore opportunities for further cooperation. The delegation included Mr Christiaan Goeman Borgesius, Senior Director – RME Operations; Mr Jubil Thankachan, Director of MarineRead More', 'SLPA and MSC mark a major step in expanding Colombo Port’s capacity and strengthening Sri Lanka’s role as a regional maritime hub.\n\n\n\n\n\nThe Sri Lanka Ports Authority (SLPA), on 4 November 2025, marked another milestone in the development of the Colombo East Container Terminal (CECT) withRead More', 'A delegation from the Port of Antwerp-Bruges recently visited the Sri Lanka Ports Authority (SLPA) to explore new avenues for collaboration and to reinforce long-term maritime partnerships.\n\nThe delegation was led by Ms. Maartje Driessens, Head of Business Development, and Mr. Achille Sobry, AssoRead More', 'DelegatesThe Sri Lanka Ports Authority (SLPA) was pleased to host a guided visit to the Port of Colombo for foreign delegates attending the Chartered Institute of Logistics and Transport (CILT) International Convention 2025. The visit, held in this morning, where the delegates were taken on a guiRead More', 'The U.S. Embassy in Sri Lanka, through the U.S. Department of Commerce’s Commercial Law Development Program (CLDP), hosted a specialized workshop in Colombo from September 8–10 that brought together legal experts from the Sri Lanka Ports Authority and the Attorney General’s DepaRead More', 'In the pic., SLPA’s Chairman - Admiral Sirimewan Ranasinghe (Rtd), Vice Chairman - Eng. Herath M. P. Jayawardhana, Managing Director - Eng. Ganaka Hemachandra, Habour Master - Capt. Nirmal Silva, Director Security - Air Vice Marshal Dilshan Wasage, The US visiting team including, Ms. Jayne HowRead More', 'In a significant step toward strengthening Sri Lanka’s position as a regional maritime hub, Maersk Line has signed a three-year Terminal Service Agreement (TSA) with the Sri Lanka Ports Authority (SLPA). The agreement is expected to foster business growth, enhance operational efficiency, anRead More', 'In the pic., are SLPA’s Managing Director - Eng.Ganaka Hemachandra, Director ( Marketing and Business Development) - Mr U. Kumara, and Chief Engineer (Development) - Mr C. L. Dasanayake\n\n\xa0\n\n\n\n\nThe “Gateways to Growth” webinar, held virtually on 12 August 2025, marked a signifiRead More', '"Today, we are profoundly honoured to commemorate the 46th anniversary of the Sri Lanka Ports Authority. We extend our deepest appreciation to our valued stakeholders, maritime collaborators, port users, and dedicated personnel, whose enduring allegiance and strategic synergy have served asRead More', 'During the meetings, both parties acknowledged the complex environment in which modern ports operate, including fluctuations in trade volumes, evolving regulatory requirements, rapid digital transformation, and increased environmental considerations.\n\n\nA delegation from the Sri Lanka Ports AuthoritRead More', 'A high-level Japanese business delegation led by Mr. Bokuto Yamauchi, Chairman and Group CEO of Expolanka Holdings Group, recently visited Sri Lanka for discussions with the Sri Lanka Ports Authority. The engagement focused on exploring future prospects for the Port of Colombo as a regional logisticRead More', 'Marking a historic milestone for Sri Lanka’s maritime industry, the ultra-large container vessel (ULCV) MSC MARIELLA, one of the largest container vessels in the world and the largest in the MSC fleet, made its maiden call at the Colombo East Container Terminal (CECT) of the Sri Lanka PortsRead More', 'A high-level delegation from Hapag-Lloyd, one of the world’s leading shipping lines, met with the Sri Lanka Port Authority’s Chairman -Admiral Sirimewan Ranasinghe and\xa0 the\xa0 Managing Director – Eng. Ganaka Hemachandra on March 4, 2025. SLPA’s Vice Chairman &ndashRead More', 'On this morning, 10th January 2025, His Excellency Akio Isomata, the newly appointed Japanese Ambassador to Sri Lanka, made a notable visit to the Port of Colombo, accompanied by two distinguished officials from the Japanese Embassy in Colombo. The delegation’s visit marked an important momRead More', 'A high-level delegation led by Mr Shohei Hara, Senior Vice President of the Japan International Cooperation Agency (JICA), visited Colombo Port yesterday to assess the progress of current operations and review the impact of previous JICA-funded projects. Mr Hara was accompanied by Mr T Yamada, ChRead More', 'Operations at the Jaya Container Terminal (JCT) and the East Container Terminal (ECT) of Sri Lanka Ports Authority (SLPA) at the Port of Colombo \n\n\xa0\n\n\n\n\nThe Sri Lanka Ports Authority (SLPA) Terminals have reached a historic milestone as of December 31, 2024, handling over 2.4 million Twenty-FooRead More', 'The Chairman of the Sri Lanka Ports Authority, Admiral Sirimevan Ranasinghe Rtd., addresses the event.\n\n\xa0\n\n\n\n\n“We have entered an era where we must identify our weaknesses, overcome them, and work together for the success of the country,” stated Admiral Sirimevan Ranasinghe Rtd., ChRead More', 'MV. Navios Unite being operated at the Jaya Container Terminal (JCT) of Sri Lanka Ports Authority (SLPA)\n\n\xa0\n\n\n\n\nUnifeeder’s MV. Navios Unite operating the Asia Gulf India (AGI) service recently made her maiden call at the Port of Colombo. To mark its arrival at the Jaya Container TerminalRead More', 'In 2024, Sri Lanka Ports Authority (SLPA) terminals achieved their highest-ever throughput, reaching 2.41 million TEUs amidst competition. SLPA alone contributed 2,413,012 TEUs, emphasising its vital role in the port’s performance despite ongoing construction at both terminals. The Port ofRead More', 'Eng. Ganaka Hemachandra, Managing Director of the Sri Lanka Ports Authority (SLPA), expressing views at the discussion.\n\n\xa0\n\n\n\n\n“A project and process are currently underway to utilize land owned by the Sri Lanka Ports Authority (SLPA) and the Port of Colombo (POC) for solar energy harvestRead More', '“There will be no politics in the ministry. Our focus will be on uniting both the private and public sectors to move the country forward.”\n\n\n\nThe Minister of Transport, Highways, Ports, and Civil Aviation, the Hon. Bimal Rathnayake, officially assumed his duties at the Ministry yesterdaRead More', 'A part of the CBRNE at the Port of Colombo\n\n\xa0\n\n\n\n\nOn November 19, 2024, the Port of Colombo conducted a Joint Emergency Response Exercise focused on CBRNE (Chemical, Biological, Radiological, Nuclear, and Explosives) scenarios. The exercise brought together key agencies, including the Sri LankaRead More', 'The recent courtesy visit by The Colombo Plan to the Secretary of the Ministry of Ports and Aviation and the management of the Sri Lanka Ports Authority (SLPA) represents a significant step in strengthening collaboration and updating attendees on recent developments and initiatives under the MariRead More', 'Pic:\xa0Admiral Sirimevan Sarathchandra Ranasinghe (Rtd) assumes duties as the Chairman of Sri Lanka Ports Authority \n\n\xa0\n\n\n\n\nAdmiral Sirimevan Sarathchandra Ranasinghe (Rtd) aasumed duties today (10/03/2024) as the Chairman of Sri Lanka Ports Authority (SLPA).\n\nHe was the Commander of the NavRead More', 'SeaLead Shipping, a rapidly growing global shipping line, officially inaugurated its new direct liner service in collaboration with the Sri Lanka Ports Authority (SLPA) today, October 2, 2024, at the Port of Colombo. This significant development enhances maritime connectivity between the Far EastRead More', 'Today, on World Maritime Day 2024, the global maritime community unites under the theme, “Navigating the Future: Safety First!” This year’s theme accentuates the vital importance of safety in all aspects of maritime transport, from seafarer welfare to shipping operations and envRead More', 'Hon. Minister of Ports and Civil Aviation, Mr. Vijitha Herath assumes office. The Secretary to the Ministry of Ports and Civil Aviation – Mr.K.D.S.Ruwanchandra is also in the pic.\n\n\n\xa0\n\n\n\n\nThe newly appointed Minister of Ports and Civil Aviation, Mr. Vijitha Herath, emphasized the nRead More', 'MV EVER ARM at the Colombo East Container Terminal of the Port of Colombo\n\n\xa0\n\n“The call is testament to international shipping trust in Port of Colombo”\n\n- Keith D. Bernard, Chairman SLPA\n\n\xa0\n\n\n\n\nThe container vessel MV EVER ARM made its first call at the Colombo East ContainerRead More', 'We are pleased to announce the port call of the container vessel EVER ARM at the Colombo East Container Terminal (CECT) today, 5 September 2024. Sailing under the flag of Taiwan, this ship, identified by its International Maritime Organization (IMO) number 9893931, marks a significant milestone forRead More', 'His Excellency Andrew Patrick, the British High Commissioner to Sri Lanka, accompanied by officials from the British High Commission, made a courtesy visit to the Sri Lanka Ports Authority (SLPA) today, 29 August 2024. During their visit, the delegation met with SLPA Chairman Mr. Keith D. BernardRead More', 'As of August 2024, Colombo Port’s container handling has seen notable growth: SLPA increased by 16%, SAGT by 10.4%, and CICT by 5.0%, contributing to an overall port growth of 9.6%\n\n\xa0\n\n\n\n\nThe Sri Lanka Ports Authority (SLPA) has noted recent reports in certain local media outlets suggestiRead More', 'Mr. Keith D. Bernard - Chairman of the Sri Lanka Ports Authority(SLPA) speaking at the event.\n\n\xa0\n\n\n\n\nMr. Keith D. Bernard - Chairman of the Sri Lanka Ports Authority (SLPA), attended as Chief Guest at the 14th All India Maritime and Logistics Awards (MALA). The event took place at the JW MarrioRead More', 'The Sri Lanka Ports Authority executed a rapid response to avert a major catastrophe by successfully containing a fire on MV “MSC CAPETOWN III” at Port of Colombo.\n\nThe Sri Lanka Ports Authority (SLPA) reports that swift and coordinated action successfully averted a potential disaster foRead More', 'The Sri Lanka Ports Authority (SLPA) celebrated its 45th anniversary yesterday (1 August 2024) at its Chaithya Road premises with religious activities. The event was spearheaded by the Minister of Ports, Shipping, and Aviation, Hon. Nimal Siripala de Silva.\n\nThe SLPA, established on 1 August 1979Read More', 'Reflecting on 45 years of Sri Lanka Ports Authority’s transformative impact on Sri Lanka’s ports while envisioning continued growth and excellence in the maritime sector\n\nGovernor Joseph West Ridgeway, in\xa0Review of Administrative Affairs of Ceylon\xa0(1896-1903), lauded CoRead More', 'Recognised for Outstanding Growth and Performance in the First Quarter of the Year by Alphaliner\n\n\n\n\n\nThe Port of Colombo has achieved landmark recognition by being named the best-performing port globally for the first quarter of 2024 by Alphaliner, a leading information platform for the linRead More', 'National Defence College Course Participants Visit Port of Colombo for Economic Security Module\n\n\n\n\n\nToday, a group of course participants from the National Defence College (NDC) conducted a study visit to the Port of Colombo as part of the National Security and Strategic Studies (NS&SS) course.Read More', 'Secretary to the Ministry of Ports, Shipping and Aviation - Mr K.D.S Ruwanchanda, SLPA Chairman – Mr.Keith D Bernard, Senior Consultant Team Lead- Maritime Advisory Programme of the Colombo Plan – Mr.Rohan Masakorala, and General Counsel and Chief Administrative Officer, Virginia Port -Read More', 'U.S. Embassy in Colombo Hosts Event on Sustainable Development in the Ports Sector\xa0in conjunction with the Indo-Pacific Business Forum in Manila\n\n\n\n\n\nIn conjunction with the Indo-Pacific Business Forum in Manila, the U.S. Embassy in Colombo organized a satellite event themed “Driving SustRead More', 'In the pic., are Secretary to the Ministry of Ports, Shipping and Aviation - Mr K.D.S. Ruwanchandra, Chairman of SLPA – Mr.Keith D Bernard, World Bank Senior Economist - Mr Dominik Englert, IFC Transport Sector Specialists along with SLPA and Colombo Plan officials.\n\n\xa0\n\n\n\n\nThe Sri Lanka PRead More', 'The East Container Terminal of Sri Lanka Ports Authority welcomed three more Ship-to-Shore (STS) cranes, bringing the current count to six out of the planned twelve. This progress represents a significant milestone in the terminal’s expansion, emphasizing our commitment to maintaining a leaRead More', 'Mr. Prabath J. Malavige - the Managing Director of SLPA presents a special memento to Hon. Yoko Kamikawa - the Japanese Minister for Foreign Affairs in recognition of her visit at the Port of Colombo (POC). His Excellency Mizukoshi Hideaki - Ambassador of Japan to Sri Lanka, Capt Nirmal P. Silva - SRead More', 'Increase attributed to various factors, including the Red Sea crisis and its wider implications\n\tTotal transshipment volumes expand\xa024.20% YoY\n\n\n\n\xa0\n\n\n\n\nThe Sri Lanka Ports Authority (SLPA) yesterday announced it achieved a record 48 percent Year-on-Year (YoY) increase in container volumRead More', 'The Port of Tianjin, China, has expressed its willingness to assist in transforming the Port of Colombo, currently operating as a global container port, into a green Port Said Chairman of the Port of Tianjin, Chu Jin during a meeting with Minister of Ports, Shipping, and Aviation – Nimal SiRead More', 'To enhance operational efficiency, the Sri Lanka Ports Authority has started installing ship-to-shore (STS) gantry cranes on the fifth phase of the Jaya Container Terminal (JCT). These cranes were temporarily installed and used for operations at the East Container Terminal from 2020 until the comRead More', 'MAERS

In [8]:
read_more_links=[]

for i in news:
    read_more_links.append(i.select_one("a").get("href"))
print(read_more_links)

['https://www.slpa.lk/port-colombo-page/3e0042fdcb7ba3b177166b0c43415dc8/7de91ea391abe53ccfd2a45353479538888d3436', 'https://www.slpa.lk/port-colombo-page/433013b7a5b15829f0bec1f2561acd19/492d70dfbe4b9ba7768685ea34092d3efddf5005', 'https://www.slpa.lk/port-colombo-page/9262e427d7078a34e470f0f10146a917/50ee48b41eec428db471f31ce432875eba2900df', 'https://www.slpa.lk/port-colombo-page/b4a638168861512d60f5bb3f605d9ed8/5f4a9eed713bab175d5deeae7242afb57cec36b6', 'https://www.slpa.lk/port-colombo-page/803c048e29dd1c777d0beafc7b6af8d8/db261e09cbb380d9b251b8921703947d1a1084ce', 'https://www.slpa.lk/port-colombo-page/4e004c93790015a83ddd083f9cf1022c/3f8caa57399a46e753cbf58589ad766ba4087c50', 'https://www.slpa.lk/port-colombo-page/00c4829495de6c3087450a49c1070292/87716c87bae66701c81840c2dff899fbe2117bd7', 'https://www.slpa.lk/port-colombo-page/790afcbff9c950dc945f87fb4efe38b7/e4683404e683048be31eebac9132552e1381f58d', 'https://www.slpa.lk/port-colombo-page/2faddc74b2c71847723ab5b58b8f2ce2/e8fb23172bc69cd18d034dc1d67791b9e394c15a', 'https://www.slpa.lk/port-colombo-page/fc2d9427e6caa633427f9d1e7e4b572c/f5186534697c1990de3000c43f73c65777e836af', 'https://www.slpa.lk/port-colombo-page/1d6faf95fd8c4aeb30c83d4747929f8d/af97a5548eecaf42d5e3bfb3bba0c127d6c3b2ce', 'https://www.slpa.lk/port-colombo-page/8849c3d9b808e9ec1d13967aca576c50/ae6454cfb36e7eba7874b529bfc2e4893f64b20a', 'https://www.slpa.lk/port-colombo-page/8af483bc4d52cad35dd4872a2ca1b57e/5c0e47a97295585874c61e61a7f27739eda668f8', 'https://www.slpa.lk/port-colombo-page/f511fec81acc5b618c7e9c6fab3a327a/b4924171ecf015d604e8bb3e6a33dc81789d6517', 'https://www.slpa.lk/port-colombo-page/91448fbeb01a8c605d6c9f894affae02/ac5fab91c23b67cbdcfc002023e213e2d738f106', 'https://www.slpa.lk/port-colombo-page/0ce0026b2e7d0b8a3f138d2caec7839d/ee4073e31989cf702e2b4e364d1176c9269c6a6a', 'https://www.slpa.lk/port-colombo-page/6ccc3e0a38f598a75cfdd4cadda947bd/9e32ec57e1329435fde9987c37210be3cdf73c20', 'https://www.slpa.lk/port-colombo-page/4dc3aee55462406f6b399ee87f007a8c/63226778672a72e68e507df85ccda3241ea20bf9', 'https://www.slpa.lk/port-colombo-page/9d7b00d3c44ddbdbab657a75c55048ae/549a6d8b12df720bfbda667f46d61f449dec95a6', 'https://www.slpa.lk/port-colombo-page/e478961f1b7250c90c0460d6e45d0ef8/604495ec02ac8adbef44c5f804348456ae87b86c', 'https://www.slpa.lk/port-colombo-page/86af2a89c2cc4c653f6b44858708923b/cbd701d605c1dc40f66c12fd8db4cb80daa90bc4', 'https://www.slpa.lk/port-colombo-page/c4d381f6dab7d643b55ab4ddca9bedd1/f2d83518080dc01a48fba36ba040fa9f04ae04ab', 'https://www.slpa.lk/port-colombo-page/d8bdd9dca1340e313922ca07e9392e4f/8aac65045928e6f6fb9fdb263c4fa557053b4713', 'https://www.slpa.lk/port-colombo-page/4a35ed8945de9453248b70e1611982e7/8845c04e2449d6933692f6465bc6ba695b49364c', 'https://www.slpa.lk/port-colombo-page/3f2c76f5b8996ccad706248576fb43a7/27e9077ffb018a2965e6968b17bae2990b856d67', 'https://www.slpa.lk/port-colombo-page/5bb308f2447673c9ab87c5e36b6dba20/8af2148735c7a6a1e756a99c5b4b5992c2f45b49', 'https://www.slpa.lk/port-colombo-page/c759ae4ae774ee468a8bbf6e24f4b652/af09fa05a9352304557e948db57708f34e9ec117', 'https://www.slpa.lk/port-colombo-page/276a0ea77e79f56dd8ab00144d0d08e6/c3843fb3866f715a2b2f9dd46fb8ae6dd090cf62', 'https://www.slpa.lk/port-colombo-page/1cee5691decf1cb00dee3398b6bba945/d5b8f759e0a8de68c83869c047982bdab12220bb', 'https://www.slpa.lk/port-colombo-page/06317e5edfa2399761616ce5f7d2fc9b/5b8ecec3e7e9c70361242c9f3347337b975a27e0', 'https://www.slpa.lk/port-colombo-page/be015d00db175725c585ba042cfb6900/7b968c009f7178f2a67b035cf1af919220faaa98', 'https://www.slpa.lk/port-colombo-page/1f49b8d1e2397baa8f984ae025f45cf9/cb1c25fc7ecff454fc2a6e3502eba51edaa13411', 'https://www.slpa.lk/port-colombo-page/658b0c098321acc0e7c8228e37d12285/811d96d4aaf05f8c04a8923659dd6a6fc3f38dff', 'https://www.slpa.lk/port-colombo-page/c7c01226864675a92220ec6ae3c1915e/b6a77eb3c23927867b0b2af217329201aa7b221e', 'https://www.slpa.lk/port-colombo-page/d47f22cd47f20128d7ab46feca6e6f9c/b44fe65c2da5690b8a423dfa0b1657f744ab4ee3', 'https://www.slpa.lk/port-colombo-page/3b5b48b58d3cda86078af95feb0265e0/eb41fb45417fa356b4739a472290dfca4830d425', 'https://www.slpa.lk/port-colombo-page/9b83357980bad738617ae8d14afc468a/20c39c868cb92e7571b7740a71be15ec4c3255ce', 'https://www.slpa.lk/port-colombo-page/6fde5cabbeb8998302ab0001a9cfcbe2/ef7825574bdea31f5b2afe704f6ead7236f9ea71', 'https://www.slpa.lk/port-colombo-page/b106c9cac9b38b8ec3506d0f5a39d3c4/0234b49fd252e53a0d988619ee47bdd964bf4e89', 'https://www.slpa.lk/port-colombo-page/13aa3390b1cc8d99df61c74a5ba36732/a8dba8c7f844a4f637a685f13df6e1280ba4dad5', 'https://www.slpa.lk/port-colombo-page/7b9a40b4e23dfac6a5d7fe37b99a8f1d/e0e6418357fb6884acbbfdf57775c150441ea6f8', 'https://www.slpa.lk/port-colombo-page/048736b71385851679681cf34d60ebcf/b3aaf503a030469395db3ef38b274f70565e1e01', 'https://www.slpa.lk/port-colombo-page/b77531b0b1d1529d5de85e5c9f1ecdcc/b467f45330b1ca1269bb8f239cd93f40afb26d12', 'https://www.slpa.lk/port-colombo-page/1949f922c0a690438ccf859201af2f37/b739fd3529911c9eeeb1e356f7f3331c135fae7e', 'https://www.slpa.lk/port-colombo-page/6d6fbeca36cd1bcdf62af40b8c529deb/15353b3885c5848e3b696e1a23fd3ba71062969e', 'https://www.slpa.lk/port-colombo-page/b0a2f3183d24c59a98b1ae6ecfd6671a/aa002483f48ab601afc2fe281e5b4be06326c709', 'https://www.slpa.lk/port-colombo-page/1ea16190d1112cb232df065ffa425434/73e8f7049f84dd5c3e6f1f7950b0b315ef0cd1cf', 'https://www.slpa.lk/port-colombo-page/a1e8ea5615c0c13b6a6ce03db9d739ee/70c02721d3a88f4e5156c90f8928ae4abe1668b5', 'https://www.slpa.lk/port-colombo-page/55f05756073153f5e2103480682dbd4b/717259d6c997c85e9ef95e2c6f77ae6761407349', 'https://www.slpa.lk/port-colombo-page/df5781321e7f984a9752efd922192e61/880bd5e2b3fc0623a8017f8d7f70caf090dd034f', 'https://www.slpa.lk/port-colombo-page/7e749093853ecbbe27a744e54b55174a/547555dcb4acd0190596fced90b1b25ef29ecbe7', 'https://www.slpa.lk/port-colombo-page/d20d386695c16b5cdde259f5f57d45e7/aae938737a267a9b734352debc86b5afdbdf32a9', 'https://www.slpa.lk/port-colombo-page/72c4019c32a404a433b83b84f2775a7d/a52380d5189b850edde4d6d73f45aafe2b863216', 'https://www.slpa.lk/port-colombo-page/b0d4c86ca3130db3de2ed89ec3fbdb9e/93ff82c26401ee3bd294c7055ad48a3882713de5', 'https://www.slpa.lk/port-colombo-page/4345bc9d9c2dae47d9a69cf0972d672a/150f6172e09a944ef8e777cf2c18cedd4894eb28', 'https://www.slpa.lk/port-colombo-page/6a42269e16c894d64e18ec1b2c058f62/ba0f3733e72cac80f0efbc47539b2d91a1eb7140', 'https://www.slpa.lk/port-colombo-page/cedfd4fa1dc004a9803c5a9580e126d9/b34b81b99eabb5e174e80782a0a76db9e0bd7694', 'https://www.slpa.lk/port-colombo-page/045c0d5e746859e2c38bee83bac2ce24/9bf9cdada6cc931b750d82adedf960fa13655bcb', 'https://www.slpa.lk/port-colombo-page/fd5bd1cd02a887a079a3cd3008aa05b5/3bd8820cad8970d02ed391bc6e1572bf28cf220d', 'https://www.slpa.lk/port-colombo-page/4863b0b027fbb790ff626e7dee23fc7a/c8e3fe8bef46f5dbf9d403941abd52d1b9811142', 'https://www.slpa.lk/port-colombo-page/ad4660820f68d59766a72c4f0b528a80/2c0ee0bd64e8d4ecfe1daf1acfdfde3b55d8e5cd', 'https://www.slpa.lk/port-colombo-page/ed367887c6e3f6d4f29d48b7e5e4fafd/746d557d64e35b6d695aac392400efef7a206b8b', 'https://www.slpa.lk/port-colombo-page/f7ca934c101f8fe086fa5f3ecb805b8c/413a3d787d45f2767ce7143adf701dbd579c411e', 'https://www.slpa.lk/port-colombo-page/e437becee41a9fad0547d0d49d48fe75/38aac0ddc2cca9f8d209c24108445d4a47dc0d29', 'https://www.slpa.lk/port-colombo-page/ee7c04533e1b386269dfb94aa1dcc64d/9919d4896971917ce9a69f108a36de0a9c0fb536', 'https://www.slpa.lk/port-colombo-page/be70246711a54686a92f5233564212b2/7dd4140a0e61d282ee8c2362735146fb01394d5b', 'https://www.slpa.lk/port-colombo-page/4ec240d7eefc6840dcb251c8a0737ac0/29e9b99947ff9e3a3acbb0b17c0095a27b353efa', 'https://www.slpa.lk/port-colombo-page/bab30a822b63e012a1afe71bfbd6fdb7/0257c46e5eba685ae2faee4188b19d5ae1c0fc1d', 'https://www.slpa.lk/port-colombo-page/6db408245420e3b0ddcd1c64adca84b2/96159a47d1c8dc774081fd3bb6d4165168a16dfe', 'https://www.slpa.lk/port-colombo-page/d5adf2a41e3be2f4d97b8f5edeba305f/f6a634cb8c77f4f38cf76d6a73a709ea7a36a4f9', 'https://www.slpa.lk/port-colombo-page/2be5348547a9067a885f45a38ee1bf87/95c4d989bada5942d57cdf79bc4a94061d9f5ed5', 'https://www.slpa.lk/port-colombo-page/c2d8d36d0388eb94870f57d4991087e1/eb5d8f2af40f030249f13f94d74c39c57a10c723', 'https://www.slpa.lk/port-colombo-page/737bd956d4508079c98d8637e4b98e8a/1abb49e72fa7be98d85d7522fa75a6bd18262599', 'https://www.slpa.lk/port-colombo-page/01af6c4b2eea4da413544322f4e3aa48/8c9829f1668cc58ee1a90cfaa48bc3d2643c50c8', 'https://www.slpa.lk/port-colombo-page/13dec3bace4fa01a4ad6ee878c96785b/651a37377101ee33926bd7ec0a7bb73717c8cdfe', 'https://www.slpa.lk/port-colombo-page/18d5e4b023050e13932e0b11b9f564bb/c53b8718b9a20a8a1e6c53dfc110681ad1cddadf', 'https://www.slpa.lk/port-colombo-page/ac139510d7d4e0ca070e38bfe6d12850/3574fe173b1f5f065fe918c23d24b522e50a4319', 'https://www.slpa.lk/port-colombo-page/40477d928b6a07b16ecf2e48b12ad5aa/27c96eebdb68f3b83634371c25906473ff75ff08', 'https://www.slpa.lk/port-colombo-page/f41bfc304a0a0339d3094ba86b12b457/87559002e98c84fb8462e4b56f098da10604524f', 'https://www.slpa.lk/port-colombo-page/cbf715e89fed0d8f4ab0ab8dd93af550/f44ae1b6c9f93e767788fe4913f86fc1ea13b248', 'https://www.slpa.lk/port-colombo-page/fb40f321c6eef7ac90181aa6e91e76f7/cc3cbb1fe4f14e7701a9eff915d683d028339de7', 'https://www.slpa.lk/port-colombo-page/76fb6cff30d902ed8f5f0bb780cfd4ad/731a8e9586112136d3a82a5836a7cb5328ee5be6', 'https://www.slpa.lk/port-colombo-page/6269b699f8b2cc2bd511b9baec5c73e4/e2bcba22370bf289bcd834c721cf8a1c181e9043', 'https://www.slpa.lk/port-colombo-page/e5912c24eafcd7b14b2c85b4e39f5b34/45a09d10de71ca0e34c17473d87c2a02e292e446', 'https://www.slpa.lk/port-colombo-page/148ce71d2cc6699cf3c16c51c4998b8e/8a1a650fac0df6686ebfbd04c9d7111e1e0d5b82', 'https://www.slpa.lk/port-colombo-page/1d641c5bdb201c1d094f3f8b2b695043/3a1509a3e58970ca62908a00b6825b92049ab5fd', 'https://www.slpa.lk/port-colombo-page/ed72576f114ee37abe8b8028e3d5ad09/3740308d39a35c638d7da33f33c873233bcba697', 'https://www.slpa.lk/port-colombo-page/8ef466a0b7ad5103a8a0e255a43d23a1/478e25938d77cfd68638e8159d7a22ad89bf53bd', 'https://www.slpa.lk/port-colombo-page/1ac059587551356670ee8bb0d465fd69/93a74bf962bc2778cdeb3ab19dd3d4274528d46d', 'https://www.slpa.lk/port-colombo-page/4bb20bf41262186ab336e1c77882d734/721d3fe11b501d373afc6054123cd03249496413', 'https://www.slpa.lk/port-colombo-page/6bfb88bf7283c3563c5ec8a52bca3ea9/9c16b7cf251bb56b0e179caa97998bc35ad8d76c', 'https://www.slpa.lk/port-colombo-page/61ba311e0652507d75c1f2905caf4ad4/f90e21343a6352347553e64c83eafbd21805d56a', 'https://www.slpa.lk/port-colombo-page/cc3d22ea6e6960ba9343fb8f96564337/90bf770de801a67b120a7c8c6388be3b51fd80d5', 'https://www.slpa.lk/port-colombo-page/8aa0034991e5bb6e0e17a43b24e3fbf2/a27289aa934a7f75fcc5f5c79a17d1b2704c2bff', 'https://www.slpa.lk/port-colombo-page/85e5452ca528a3a755efce58c3600000/cfcac2cce9c6b7ad7591dfe576b797473588a83c', 'https://www.slpa.lk/port-colombo-page/20949f9e7e498ceef9192d84818e2693/758f5868fe62e09b196ae4b68f5bd06762b9f514', 'https://www.slpa.lk/port-colombo-page/8c94bc875ad199cb5140142924e7135e/2781927d23fb1153b401653840ed733769a9120e', 'https://www.slpa.lk/port-colombo-page/f9e93cef1502b31753a242ec58266bd9/14d480297c9d84ccfb3bcc15c7b4af47a7df3399', 'https://www.slpa.lk/port-colombo-page/451fa529d48cde6eb722f3ee476d1d49/7a351a61e7ab7a0d4d0ba44dceca3b11e583b5c9', 'https://www.slpa.lk/port-colombo-page/b6e3c1c787c764b944fca596fa7c64e0/b3047d6de5cbb838e52dbb34fcde03b09e5b9f2b', 'https://www.slpa.lk/port-colombo-page/55803a116687f67bf3beeab4797af2e7/3274f5e3c99a763a809aa10fc1ddec1b4217e9c5', 'https://www.slpa.lk/port-colombo-page/d6b584ba6dfa99a68caaac70fca104e3/7b8f29059e73478124f733ec602dde934d236d9a', 'https://www.slpa.lk/port-colombo-page/f200c495baae4de90baedc0c2b668b61/e054646e06e8342931da025a48e682a88eb872e8', 'https://www.slpa.lk/port-colombo-page/ca81f009292dd43bb24e3b96d215b4e4/45272f2c1fbc62f536f23cf07a431d9b6a565bc5', 'https://www.slpa.lk/port-colombo-page/93381353ff0858e812ba4988c123199b/5ba08fdadf755f81daf0c5f97dafcc1d5e1a28b7', 'https://www.slpa.lk/port-colombo-page/3fbf0a0fbe05f805970a220e95b7f24c/8f0eb11c1a7464ccb827cc3a0227f242cb9d653e', 'https://www.slpa.lk/port-colombo-page/7c4b9b03c6ac4f5c3a435c402a7f28de/463e3521f7be21d9b9c2650670f072c033fbb2e5', 'https://www.slpa.lk/port-colombo-page/c3bedd78f6cc744cb52fcce0b36d9bbb/28c14d0c7372d320745f630772ed1311e3ba72fc', 'https://www.slpa.lk/port-colombo-page/f6daa488ede01926808cdcfa1e1bd1d4/35e84388c6a5d1aec7f3c9f4c50ef943b96c2ecc', 'https://www.slpa.lk/port-colombo-page/1dffb9ab0f4aa22dd77bde059de46292/fafedbc919dcf0cfea125caebb2e0682abacbe38', 'https://www.slpa.lk/port-colombo-page/213b926e480d14463e47cd83a2580a4b/76afd1f182702f9cef45e8ffe929e462da86b7fa', 'https://www.slpa.lk/port-colombo-page/604d68755fe277a624c0b61dfdf65914/52f520a22ffc0cda17322daa6d47b632fc54fe3e', 'https://www.slpa.lk/port-colombo-page/acdfea68c66b0efd569332d1b1fbac45/e44d4962b74ffd9604f65a72bec6ce2130d54110', 'https://www.slpa.lk/port-colombo-page/606b97a3e048c588d83879d78de862f9/b6b912053129bea4d341807f800186cdcad8bc61', 'https://www.slpa.lk/port-colombo-page/d93529382af348d3cf252942d62d60b7/8aae6c5bf2769df25720756cd0ba9497c0918756', 'https://www.slpa.lk/port-colombo-page/2356cc850627d055f15a02d2a3ffea0c/0adc65eeea30579d0cd712d93cbab572d3fe0954', 'https://www.slpa.lk/port-colombo-page/d2503c6292141e4a9f046b51771d01d3/19455b636b03340cea3e5098f70f581c59bad140', 'https://www.slpa.lk/port-colombo-page/ff71c354d9d45d2237d3f7c37d8d636b/2aa1856f5cd841d74d08d9e2caf390c9642b8718', 'https://www.slpa.lk/port-colombo-page/f079bc853f5351d3a26269afec58f5b3/a55bcd10d34215b0a93c6d4767f517e333ad48d5', 'https://www.slpa.lk/port-colombo-page/7cba00e1cacf0b5c58810f9741f2139a/a63ee7c98fc7fc8fa3378e0372282ee6a722f0c2', 'https://www.slpa.lk/port-colombo-page/d1222546fb30284ee3c09ec45e2bb6e0/ad22f00307801cee40f544cdfdecccd25e382df1', 'https://www.slpa.lk/port-colombo-page/927177fcc0bba5e7be3a1124c25151e0/e90d8171e5159ae71e079bad942efb844251975a', 'https://www.slpa.lk/port-colombo-page/08d043571b1021c60496789a550c1389/fbce6ceda5a1211159ae992d9d7d7c46b78b5d66', 'https://www.slpa.lk/port-colombo-page/ed7ea2a569cd93d7af35a99f6ff3b0b7/13601050f7350ae4f003c282efb8b66fde655329', 'https://www.slpa.lk/port-colombo-page/1e2a9b3d2eef08c4140fa7484638cde4/b88c2333cf672a9c5182df24699a598ffa80991f', 'https://www.slpa.lk/port-colombo-page/f26d821c0668935b35f0cdc077c11b01/64456e0cd8a267c20ded30a1aeff115778e9b29e', 'https://www.slpa.lk/port-colombo-page/42cf4449133ae1942cc6c2a2b6a1c76d/c00cd22c5ffe92c185d3ea074409c05fd0a4b609', 'https://www.slpa.lk/port-colombo-page/a2e761538f9b714f3e44a7eb9787eca3/3b4d14b6963e1516ae34c3a87604d9dd1117c92d', 'https://www.slpa.lk/port-colombo-page/c37056485aba69ec6736b1646517b2fd/81af7e2d111fda8042a252a818006809de887f07', 'https://www.slpa.lk/port-colombo-page/adaff25d028e164bd40c03147d8a87b7/ec03b728777a9716c70c1f3bec84dc68b74229ca', 'https://www.slpa.lk/port-colombo-page/e9feb36dd5a0df9d4812705b9f58502b/6ef27a417f2747560059a9ce002ce085bd4e0065', 'https://www.slpa.lk/port-colombo-page/97a0934a7ce6b61469e54a1488cf3a89/b70fbde2ba6079686b4f599bed55a5e9fff8b954', 'https://www.slpa.lk/port-colombo-page/60107de679276cd4f4d178c8c5961beb/66e325dabd81be0f901cbd38ac5a4fdaf6c15f15', 'https://www.slpa.lk/port-colombo-page/a6357ad615dc31a550ecd8417cce54e1/42db447615c11ab0908f823e9fc8afb40e64128f', 'https://www.slpa.lk/port-colombo-page/3a7dfb261239dc3db221e64ef49b5694/2c29591fe9ed94d40819669c227296599af943f1', 'https://www.slpa.lk/port-colombo-page/652de8fbc49ed32b796bb442e1d157b4/c4014512109b15a66a42eb0315d3ef9e1938ce6b', 'https://www.slpa.lk/port-colombo-page/9cbc5413b1428d133325410219b494b5/e40e432cb03a527f42a008d7aa5b5d1bc7aeb178', 'https://www.slpa.lk/port-colombo-page/9880c713750cedf9cd0aaff1206ad7cc/44c67da2bf5cceff33c62c0dbf0c2aa08bdb6c84', 'https://www.slpa.lk/port-colombo-page/99e2983687da572ac643cef54e133f44/57abdc12a56fe4c5c08af143d2a4a90d00383ddf', 'https://www.slpa.lk/port-colombo-page/96f073a586ee4dadfc4964e68f954776/af18dece98503f2ca8f2e80fea2ca3d1d009d35b', 'https://www.slpa.lk/port-colombo-page/4891f6727cbec1c7a0e61edf17ca8087/dd53dce22ba3d517ab5f06d93e556057274c3ac3', 'https://www.slpa.lk/port-colombo-page/1293070b17431d743bce0e0b93dbbad5/cf83cfd27f46cc652c882190453d0fa77f79be3d', 'https://www.slpa.lk/port-colombo-page/cf7f09247c9070220cd380b24921df21/2d5ae6f49d56a67e495d9ee103a6a69ba242160d', 'https://www.slpa.lk/port-colombo-page/a58ab8a4a7e9d7259e924aa2e6840e3b/e51899692336de72f4dad425e0a45ca6586e3c35', 'https://www.slpa.lk/port-colombo-page/34e14c57775d534f86c2a2de68445f55/c408321f9bcc7fe85199d6fa2a8138f2fa2c4a36', 'https://www.slpa.lk/port-colombo-page/d02b0a7b50b35ca9b7d88bfab2c9b9e0/8c87ccc3482779f7ba5b85010340b2e5fe9256d3', 'https://www.slpa.lk/port-colombo-page/dffcccf93e9d38af18d3f4c2540bc1bf/58fbb604c0702a8206068b734d5d7296737bf557', 'https://www.slpa.lk/port-colombo-page/b5c77cd779cc5a28aeda198cff444e85/8da65bd292d238fae147efbf8ee97d1202348be3', 'https://www.slpa.lk/port-colombo-page/56b9e5877b0e201ec4583743a6de3b95/6c7a0aa18516e274f4cc95854928fd823f425e89', 'https://www.slpa.lk/port-colombo-page/4a1dbc720ed3d16f2dbf5552d56c0cab/c9cf257d2262ce1b3c5f5695865c802ce7553e40', 'https://www.slpa.lk/port-colombo-page/b006b62d1ecf198373b9290a47e45f1a/f089ce33fa3580898bf45bdebaeed3a6612add77', 'https://www.slpa.lk/port-colombo-page/971f6f295f130be9dc66fc3fd209ad6e/6c7ae77182f0dd6cd4fc4f4b415a8e806e2e7c82', 'https://www.slpa.lk/port-colombo-page/84aa350a3f855e159498ca73f3667af0/ddc4dbb7f26d08554065ba0404bfbbee9b89a503', 'https://www.slpa.lk/port-colombo-page/9353e59fa09171d77156924340e3d47a/ecf56a0b01090220d9e8fbc71a209a330360f491', 'https://www.slpa.lk/port-colombo-page/53e5b33a60b60fa10466ef169d64f011/6148c20c54db98d2619a08b075e825c885d49b89', 'https://www.slpa.lk/port-colombo-page/6777919b97d317150b19422f885ae9e9/e4fe4f453b9f97bd920422d659d2aa1824438e6c', 'https://www.slpa.lk/port-colombo-page/bdeade655ebf1d8b5b4e864e7e8ff83b/72b337f9551bc2b57987b2af488918b01e84a8c4', 'https://www.slpa.lk/port-colombo-page/8d2cabf399622f52daae69d345af8ec1/acb0784370ffc6d004098ac6ff9ffffad4546fb3', 'https://www.slpa.lk/port-colombo-page/ea6e643f564988558fa17de5de086501/c051ca66aacab50833c3cadaf3281cecd77c6e2b', 'https://www.slpa.lk/port-colombo-page/79f2adf7b7a247afc1b83f7d4acc183d/7dc8aa3acdec16368684c48f8bd189a0fecba8ca', 'https://www.slpa.lk/port-colombo-page/8737dbe73c5160a85fadee591ebbd3f5/81a83b8d03c0326d6322c81046ba3c36473052ec', 'https://www.slpa.lk/port-colombo-page/01f07e65325176410dcec6af2d0c7dbb/ae5a2094650220050a126bfb20319d1444348c85', 'https://www.slpa.lk/port-colombo-page/ce23d650a975a799738cf9fb558a454c/cd9f0d6ad2121ecfb649e129fa8a2a059bc9c44e', 'https://www.slpa.lk/port-colombo-page/dfc2993d5c3e8ad6b1bf06733b5b05c9/50ea6798de0d61ed6b05588d5697922db794c4c0', 'https://www.slpa.lk/port-colombo-page/55f7d2e7b7ce11358d3b77802e4ce9d0/4aed738d214ea6b9451d61d2c1104e49ae4254df', 'https://www.slpa.lk/port-colombo-page/fbf7f45a43376dd4c007c01734c286cd/8351e502a2272333b67381bc1066bf83f29c877c', 'https://www.slpa.lk/port-colombo-page/4e65d9c7fde07049b84685a1ddd37901/fe81abd747cb1a644c34a6911d309f14803975f7', 'https://www.slpa.lk/port-colombo-page/64423fdea11d8adf060e116d82f16c8d/247f21be3dc5bed49e1524d6e07bead523a38471', 'https://www.slpa.lk/port-colombo-page/ab581fd20fff92ae4b182edef557003a/c9a4cafb17f3db75e5c2e8149551138ef5144503', 'https://www.slpa.lk/port-colombo-page/edb259f0ac0cf5e9c812fa5eeef61244/5bcf49cf49e1bb24c19c24144a5db1e3886f8fc1', 'https://www.slpa.lk/port-colombo-page/3af6cd5154a7b44078eb8a44af3b1cc3/3aa16c9d170b8b1550a7f4ed21e8cdfc02fdd0b5', 'https://www.slpa.lk/port-colombo-page/cc16f92ecb077c9f1582b683ea81bd22/ac203b7f99c45dc44c79f685be47b0feefff1a92', 'https://www.slpa.lk/port-colombo-page/080a0aeb9ce10cc140fffaecd8dd6fe8/1be7a18eacaf1f83840d7b45a471d8138471c91a', 'https://www.slpa.lk/port-colombo-page/5d278ded5fd27e1aa1dca75716286f4f/80b487c506c653eec5c8b5374b9f4adc

In [9]:
news_dict = {
    "Headers":headers,
    "Content": content,
    "Read More": read_more_links
}

print(news_dict)

{'Headers': ['CMA CGM Senior Executives Visit the Port of Colombo', 'U.S. Assistant Secretary of State S. Paul Kapur Visits the Port of Colombo', 'SCO Delegation Visits Port of Colombo and Pilot Station', 'Maersk Engages with SLPA on Enhancing Terminal Productivity in Colombo', 'SLPA Signs Terminal Service Agreement with Unifeeder Lanka to Strengthen Operational Efficiency', 'CMA CGM Delegation Holds Discussions with Sri Lanka Ports Authority on Strengthening Cooperation', 'German Ambassador Visits SLPA to Discuss Port Development Opportunities', 'ADB President Masato Kanda Leads Delegation on Site Visit to Port of Colombo', 'SLPA Chairman Reviews Port of Colombo Operations Amid Middle East Tensions', 'DR. PARAKRAMA DISSANAYAKE ASSUMES DUTIES AS CHAIRMAN SLPA', 'Third Berth at Colombo East Container Terminal Enters Service, Marking a New Phase of Operational Scale', 'Colombo East Container Terminal Receives Maiden Call of Ever Eon', 'Sri Lanka and Maersk Explore Expansion Opportunities at Davos Meeting', 'SLPA Holds Discussions with COSCO Shipping', 'Ultra-Heavy Cargo Handled at Port of Colombo', 'SLPA, CMA?CGM Ink Terminal Service Agreement to Strengthen Colombo Port', 'Port of Colombo Records Historic High of 8.29 Million TEUs in 2025', 'SLPA and Maersk Deepen Operational Coordination at Port of Colombo', 'SLPA and Evergreen Strengthen Strategic Partnership', 'MSC and SLPA Sign New Terminal Service Agreement', 'Hapag-Lloyd Delegation Visits Sri Lanka Ports Authority', 'SLPA Launches Second Berth at Colombo East Container Terminal', 'Port of Antwerp-Bruges Delegation Strengthens Maritime Ties with Sri Lanka', 'SLPA Hosts Successful Port Visit for CILT International Convention', 'Strengthening Legal Foundations for Sri LankaŌĆÖs Ports and PPPs with U.S. Support', 'U.S. Congressional Delegation Meets Sri Lanka Ports Authority Management.', 'Maersk Line Strengthens Ties with SLPA Terminals', 'Gateways to Growth: US, Sri Lanka, and Maldives Forge Stronger Maritime and Trade Partnerships', 'CELEBRATING 46 YEARS OF EXCELLENCE: SRI LANKA PORTS AUTHORITY', 'Sri Lanka Ports Authority delegation visits Port of Antwerp-Bruges to advance cooperation', 'Japanese Business Delegation Engages with SLPA on Colombo Port Development', 'Sri Lanka Ports Authority Welcomes MSC MARIELLA ŌĆō The Largest Container Vessel Ever to Call at Sri Lanka', 'Hapag-Lloyd Senior Delegation Meets with Sri Lanka Ports Authority Leadership', 'Newly Appointed Japanese Ambassador Visits Port of Colombo', 'JICA Delegation Visits Colombo Port', 'SLPA Terminals JCT & ECT achieves the 2.4Mn TEUs amidst competitive environment while Port of Colombo achieves Record Growth in 2024, Setting the Stage for Future Expansion', 'ŌĆ£We have entered an era where  we must work together for the success of the countryŌĆØ  - Admiral Sirimevan Ranasinghe Rtd., Chairman, Sri Lanka Ports Authority', 'MV. Navios Unite marks maiden call at JCT SLPA', 'SLPA Terminals Record All-Time High of 2.41 Million TEUs in 2024 Amidst Competition', 'ŌĆ£The optimum usage of energy is a mandatory requirementŌĆØ ŌĆō Eng. Ganaka Hemachandra, Managing Director, SLPA', 'Minister Bimal Rathnayake Assumes Duties, Vows to Combat Corruption and Promote Unity', 'Port of Colombo Hosts Joint CBRNE Exercise', 'Colombo Plan Officials meet Port and Aviation Ministry officials to strengthen partnership', 'Admiral Sirimevan Sarathchandra Ranasinghe (Rtd), new Chairman of Sri Lanka Ports Authority', 'SeaLead Launches New Liner Service with Sri Lanka Ports Authority', 'Steering Towards a Safer Future: World Maritime Day 2024', 'Vijitha Herath Assumes Office as Minister of Ports and Civil Aviation, Calls for Integrity and Unity in Governance', 'MV EVER ARM makes first call at the SLPA controlled Colombo East Container Terminal', 'Port of Colombo Welcomes EVER ARM: A Milestone for South AsiaŌĆÖs Busiest Port', 'British High Commissioner Pays Courteous Visit to Port of Colombo', 'Clarifying Media Misrepresentation on Port Operations', "ŌĆ£With ongoing developments we are confident in the Port of Colombo's evolution as the hub of South AsiaŌĆØ       -  Keith D. Bernard, Chairman SLPA", 'Incident at Jaya Container Terminal: Fire Averted on MV ŌĆ£MSC CAPETOWN IIIŌĆØ', 'SLPA Marks 45 Years with Celebrations and Developments', 'SLPAŌĆÖs 45 Years of Excellence', 'Port of Colombo Becomes WorldŌĆÖs Top Performer in Growth', 'NDC Course Participants Visit Port of Colombo', 'SLPA Officials Visit Virginia Port:  Insights on Cutting-Edge Technology and Sustainable Operations', 'Charting Sustainable Ports: U.S. Embassy Event at Indo-Pacific Business Forum', 'SLPA officials meet World Bank  Special Team and International Finance Corporation officials', 'East Container Terminal Welcomes Three New STS Cranes', 'Japanese Minister for Foreign Affairs - Hon.Yoko Kamikawa visits Port of Colombo', 'SLPA container volumes expand 48% YoY in 1Q24', 'Port of Tianjin China expresses willingness to assist transforming Colombo Port', 'STS Cranes Shifted to JCT Phase V', 'MV MAERSK EdmontonŌĆÖs First Call at ECT of SLPA', 'X-Press Feeders wins top accolade at Colombo Ports Awards', 'Colombo Port transshipment growth surges for third month', 'SLPA collaborates with JCT, SAGT and CICT, hosts Port of Colombo Awards Night', 'M.V. Ane M├”rsk Makes Maiden Port Call in Colombo, Leading the Charge in Sustainable Shipping', 'SLPA gets brand new cranes worth $ 282 m to boost capacity at East Container terminal', "U.S. Backs Expansion of Sri Lanka's Ports Sector with Capacity Building Program for Sri Lanka Ports Authority (SLPA)", 'ŌĆ£Colombo PortŌĆÖs Bandaranaike quay to convert into a passenger terminalŌĆØ', 'Aitken Spence Travels welcomes 3 cruises in a single day to Colombo port', 'Marella Discovery 2 cruise liner calls on Colombo', 'Luxury passenger vessel RESELIENT LADY carrying 2318 passengers and 1194 crew on board calls the Port of Colombo', 'Cruise vessel Aida Bella to call Port of Colombo', 'SL mulls investment for green hydrogen & ammonia production', 'ŌĆ£SLPA to transform Colombo Port into eco-friendly facility by 2030ŌĆØ', 'Sri Lanka-India passenger ferry services resume after 40 years', 'SLPA targets Rs. 35 Bn profit in 2023', 'SLPA poised as an exemplary model for SOEs, says its Chairman', 'Sri Lanka Ports Authority ŌĆō Enquiry Center', 'Port Community System a must ŌĆō Minister', 'Talaimannar pier to be re-constructed after 37 years at a cost of Rs.1.8bn', 'Maritime Facilitation Centre Marks Milestone in Sri LankaŌĆÖs Infrastructure Development', 'Port of Colombo: Foundation Stone Laid for ECTŌĆÖs Operation & Admin Building', 'Celebrating 44 Years of Excellence: Sri Lanka Ports Authority', 'ConnectX by SLPA: Official Trailer', 'A high profile delegation from the Port of Colombo attends business promotions visit at VOC Port Authority, Tuticorin, India', 'KKS Port opens with MS Empress luxury vessel calling over from Chennai', 'MV Empress: Trincomalee Welcomes Cordelia CruisesŌĆÖ Magnificent Cruise Ship', 'SLPA Chairman and Indian High Commissioner Discuss Maritime Collaboration in Colombo', 'Minister Explores Investment Opportunities at Port of Colombo during Successful Singapore Visit', 'Sri Lanka Ports Authority Announces Appointment of new Managing Director', 'Ambassador for France visits Port of Colombo', '30 Year Development Plan of the North Port of Colombo', '30 Year Development Plan of the North Port of Colombo', 'U.S Department of Transportation officials meet SLPA Chairman', 'VIKING NEPTUNE CALLS AT THE PORT OF COLOMBO', 'Port of Trincomalee Commences night operations', 'The first vessel under port promotions programme calls at the East Container Terminal', 'Japanese State Minister of Foreign affairs Visits Port of Colombo', 'Phoenix Reisen calls on Colombo with 500 passengers', 'Lanka can become maritime hub in the region - CASA', 'Sri Lanka Ports Authority commences work in 2023', 'Port dredgers ŌĆśDiyakowullaŌĆÖ and ŌĆśHansakawaŌĆÖ resume work with MinisterŌĆÖs intervention', 'Minister instructs expedite stalled construction work at the Jaya Terminal', 'ILO, Japan partner to enhance economic wellbeing of returnee and aspirant Sri Lankan migrant workers', 'SLPA donates to the Consolidated Fund of the Government', 'ŌĆ£Ocean OdysseyŌĆØ super luxury passenger ship arrives in Colombo port', 'Colombo Port: Highest Performing Port in South Asia ŌĆō UNCTAD', 'Mein Schiff 5 arrives in Port of Colombo', 'A high profile delegation from Port of Colombo visits Bangladesh', 'Norwegian luxury cruiser ŌĆśViking MarsŌĆÖ anchors in Colombo', 'Industrial Peace vital to make Sri Lanka, a Maritime Hub in Indian Ocean ŌĆō Minister', 'SLPA Chairman meets Bangladesh High Commissioner', 'Colombo Port: Work on Colombo West International Terminal begins', 'Colombo Dockyard Launches the ŌĆ£Sophie GermainŌĆØ', 'Second Batch of Ilmenite Exports from Trinco', 'OPV P627 arrives at Port of Colombo', 'Minister inspects the ECT Project', 'Australian Navy ships arrive at the Port of Colombo', 'New SLPA Chairman Assumes Duty', 'KOICA Delegates Visit SLPA', 'Colombo Port Wins 2022 GPF Top Awards', 'Hapag-Lloyd introduces new feeder service between Colombo and Chittagong', 'World Maritime Day ŌĆö History and Significance', 'Sri Lanka: Ports as a Premier Bunker Oil Supplier', 'Minister Visits Galle Port', 'CASA Conducts 56th AGM', 'Two deep water terminals to be added soon', 'ONE launches new feeder service via Colombo', 'Thirty five SLPA employees receive Port Management Diplomas', 'Shipping industry to remove the Indian Ocean High Risk Area', 'CH Clare carrying 21,000 t of fertilizer arrives', 'Tug-boat fleet to boost SLPA efficiency ŌĆō Minister', 'SLPA: Three New Reach Stackers to Improve Operational Efficiency', 'Sri Lanka Ports Authority Celebrates 43rd Anniversary', 'New World Maritime Theme highlights environmental legacy', 'Training opens new horizons for women in ports', 'Bangladesh High Commissioner Pays Courtesy call on the Minister', 'Enhancing shipping connectivity between Chattogram and Colombo Ports', 'VIDEO: Chairman Pays a Progress Inspection Visit of East Container Terminal', 'ŌĆ£Adequate fuel reserves available ŌĆō No disruption to port operationsŌĆØ', 'My Goal Is to Increase Port Revenue up to $ 1 Billion ŌĆō SLPA Chairman', 'Japanese Ambassador Pays Courtesy call on the Minister', 'Enhance International Confidence in Ports ŌĆō President', 'Shipping Agents Reaffirm Continuity of Export-Import Business', 'Colombo the most efficient port in South Asia ŌĆō World Bank and S&P', 'SLPA refutes erroneous claims', 'Port of Colombo: Operators Rebuff Fabricated News', 'SLPA: Dedicated WhatsApp number introduces to curb fraudulence', 'CASA donates 100 bicycles to achieve Green Port objectives', 'Colombo Dockyard launches ŌĆ£Misje VitaŌĆØ, 5000DWT EcoBulk carrier being built for Misje Eco Bulk AS', 'Colombo Port terminal operators reassure global customers', 'INTERVIEW: Let us work beyond the proverbial box and take the industry to greater heights', 'Port of Colombo: CASA Commends the Commitment of SLPA and other Terminal Operators', 'SLPA: Port Services and Operations Continue Without Hindrance', 'Port Operations are Normal ŌĆō SLPA', 'Minister instructs to encourage shipping lines to pay SLPA in USD', 'Port of Colombo: Status Report', 'ŌĆ£Everything is Smoothly Going on,ŌĆÖ SLPA Chairman told the CNBC', 'Do not be misled by Fake News: On Video Circulating about JCT Operation', 'Sri Lanka Ports Authority wins the GPF Awards', 'US Undersecretary Victoria Nuland Visits Port of Colombo', 'Two posts established  for SLPA  and Ministry of Ports and Shipping  to look into  Employee Grievances', 'SLPA Launches a New Documentary Series on Global Ports', 'SLPA: Tracking the Impressive Achievements in Ports and Shipping', 'MV HR SARERA becomes first inaugural caller at the JCT after Covid-19 pandemic', '24 Seafarers trained at the Mahapola Ports & Maritime Academy (MPMA) of SLPA pass out', 'Removal of the wreck of X-Press Pearl begins', 'Bangladesh High Commissioner Pays Courtesy call on SLPA Chairman', 'President instructs release of essential items containers', 'Galle Port Development Symposium 2022: Message from the Minister', 'Galle Port Development Symposium 2022: Message from the Chairman', 'SLPA Chairman assumes duties', 'President flags off second phase of ECT', 'The Construction of the second phase of the Eastern  Terminal begins', 'Sri Lanka Ports Authority commences 2022', 'The Port of Colombo will handle over 24 million TEUs by 2040', 'Port of Colombo is the Best Connected-port in South Asia ŌĆō UNCTAD', 'SLPA Begins Booster Dose Roll-Out Against COVID-19', 'Port of Colombo is the Best Connected-port in South Asia ŌĆō UNCTAD', 'Colombo Dockyard Opens a Branch in Trincomalee', 'CHAIRMAN SLPA VISITS CASA OFFICE', 'Request for Expression of Interest (EOI)', 'WorldŌĆÖs largest container ship in Colombo', 'VIDEO: SLPA warmly welcomes Eve Ace', 'VIDEO: We are open for development ŌĆō SLPA Chairman', 'SLPA Acts timely to discharge leaky container onboard MV Thalassa Patris', 'WorldŌĆÖs biggest container ship Ever Ace to call at Colombo Port tomorrow', 'SLPA Signs the Agreement for The Largest Investment Ever In Port Sector of Sri Lanka', 'Steps have been taken to minimize the ITT delay at the Port of Colombo', 'Sri Lanka Ports Authority establishes the First Ever  Intermediate Covid Treatment Centre', 'Sri Lanka Ports Authority Celebrates 42nd Anniversary', 'SRI LANKAŌĆÖS HARBOUR DEVELOPMENT', 'SLPA Successfully Reworks Leaked Chemical Container On board', 'SLPA with ILO support commences training for seafarers', 'ECT: Bid evaluation for civil works, equipment begins', 'A greater synergy between India and Sri Lanka pivotal to handle future container volume growth ŌĆō SLPA Chairman', 'SLPA holds meeting with CASA', 'Bangladesh Support for Shipping Industry in Sri Lanka is vital ŌĆō SLPA Chairman', 'SLPA Chairman visits CICT and SAGT', 'Upul Jayatissa Appointed MD of SLPA', 'SLPA new chairman boosts employeesŌĆÖ morale for more dynamic performance', 'SLPA Chairman assumes duties', 'Capt. Keppetipola Appointed Chairman of SLPA', 'SLPA launches video series on Port of Colombo', 'X-Press Pearl Fire: Views on national misfortunes should be in good faith ŌĆō Minister', 'X-Press Pearl Fire: For the first time in decades, Port operations halt due to adverse weather for 39 hours ŌĆō Chairman SLPA', 'X-Press Pearl Fire: Fragile freights and dangerous cargo ŌĆō nature of the shipping industry ŌĆō VC SLPA', 'X-Press Pearl Fire: Harbour Master sets the record straight', 'Minister of Ports and Shipping, Chairman SLPA   join in inspecting MV X-Press Pearl', 'SLPA to Continue Port Services During the Upcoming Holidays ŌĆō Chairman', 'SLPA douses the fire on X-Press Pearl', 'My goal is to develop our employees ŌĆō SLPA Chairman', 'Colombo Port to offer thousand beds for Covid-19 patients', 'SLPA Upgrades its Terminal Management System', 'Special Notice - Finance Division Activities', 'Colombo Port is the top-ranked port in South Asia ŌĆō CPPI', 'SLPA begins inoculating employees with second dose of COVID-19 vaccine', 'Operations in the port and shipping sector continue with no interruptions', 'World Day for Safety and Health at Work', 'CPAC meets to review current state of Covid-19', 'Sri Lanka Ports Authority celebrates Sinhala-Tamil New Year', 'Sri Lanka Ports Authority launches ŌĆśTheerthaŌĆÖ Magazine', 'SLPA Celebrates International WomenŌĆÖs Day', 'CHEC donates a PCR machine for Sri Lanka Ports Authority', 'Every organization needs visionary leadership for success ŌĆō SLPA Chairman', 'A new pilot boat for the Sri Lanka Ports Authority', 'SLPA initiates Covid-19 vaccination', 'President inspects the construction of the model stalls', 'SLPA Female Gantry Crane Operators Receive Excellence Award', 'SLPA implements clearance through electronic methods', 'SLPA Launches new Edition of the Covid-19 Prevention Guideline', 'SLPA  Employees and Military Ranks of SL Army  who shouldered the responsibility of protecting the reputation of Sri Lanka Ports Authority commended.', 'Port of Colombo Operations ŌĆō Status Report', 'SLPA lays foundation stone for a new Container Freight Station', 'SLPAŌĆÖs Covid-19 Preventive Mechanism is Commendable ŌĆō Quarantine Unit', 'We wish you a very Happy New Year ŌĆō SLPA', 'Sri Lanka Ports Authority declared an essential service', 'Port of Colombo: Returns to normalcy', 'Port of Colombo Operation Update', 'Rapid Antigen Tests for Randomly Selected Groups Continue', 'SLPA Chairman meets with Army Commander to discuss COVID-19 Control Measures', 'SLPA commences Phase V of JCT', 'All Operations Return to Normal', 'SLPA perform its duties duly in distribution of imported fertilizer', 'SLPA: Port operations continue ŌĆō Minister inspects the situation', 'Sri Lanka Ports Authority declared as an ŌĆśessential serviceŌĆÖ', 'Our commitments lead us to overcome any challenge', 'Colombo Port ranked as worldŌĆÖs 18th best-connected port', 'We all have a responsibility to ensure import and export', 'SLPA: Police officer appoints to coordinate port activities', 'Do not violate the quarantine laws ŌĆō SLPA', 'Bulk carriers with fertilizers arrive at Port of Colombo', 'PCR tests carried out on another 200 at the Colombo Port', 'New Chairman and Managing Director of SLPMCS assume duties', 'Colombo Port Operations Continue Without Any Hindrance', 'East Container Terminal Inaugurates for Operations', 'Cargills Foodcity opens its branch in Colombo Port', 'Behind The Enemy Lines: Fighting the Unseen Virus ( An Interview)', 'All activities of Mahapola Academy carried out under health instructions', 'No one in SLPA infects with Covid19 ŌĆō Chairman', 'DECLARATION FORM TO BE FILLED WHEN ENTERING PORT PREMISES', 'Fresh random samples of 225 employees and port users test negative for Covid-19', 'State Minister on a special visit at the Port of Colombo', 'SAGT celebrates 21 years of maritime excellence', 'Sri Lankan Govt to expand Galle, Trinco, KKS Ports for regional, global exports', 'EDB and DCS collaborate to capture logistics sector data', 'Hon. Minister of Ports and Shipping Rohitha Abeygunawardena on a special port inspection visit at the Port of Colombo', 'Sri Lanka to become South AsiaŌĆÖs LNG Hub:  Floating storage trading facility in HŌĆÖtota from Pearl Energy', 'New Secretary to the Ministry of Ports and Shipping assumes duties', 'New MSC shipping service to Colombo', 'Hon.Minister of Ports and Shipping Rohitha Abeygunawardena assumes duties', 'Sri Lanka Ports Authority celebrates 41st Anniversary', 'SLPA assures safe handling of dangerous cargo under UN regulations', 'SLPA contributes Rs. 18.6 million to PresidentŌĆÖs Covid19 Relief Fund', 'Sri Lanka Ports Authority signs agreement with SLT', 'Mahapola Ports & Maritime Academy to resume training programmes', 'President floats committee on JCT and ECT', 'Seafarers are the forerunners of maritime industry', 'Our commitment to onboard training excellence: The legacy will continue', 'Euro Spirit Arrives Colombo Port', 'Mahapola Maritime Academy and Rakna Lanka sign MoU to boost maritime education', 'Sri Lanka wins new business providing services to Cruise Ships anchored outside Colombo Port', 'No One in Colombo Port Infected with Covid-19: PCR & Antibody Tests Confirmed', 'Employees and Port users of Colombo Port undergo PCR tests', 'Cruise shipŌĆÖs crew arrived at Colombo Port sends home country safely', 'SLPA Guideline for Eradicating Covid-19', 'SLPA: Operational Strategies during Covid19', 'SLPA launches the Guideline for Eradicating Covid-19 Pandemic', 'New Nursing Quarters for the IDH hospital opened', 'New procedure for MCC and LCL delivery of cargo to ease delay during Covid-19', 'DonŌĆÖt be misled by fake news: Port operations are continuing ŌĆō SLPA', 'Response from Sri Lanka Ports Authority to fake news', 'Covid-19 restrictions are no obstacles to release vehicles imported at the Port ŌĆō Sri Lanka Por

In [10]:
import pandas as pd

news_df = pd.DataFrame(news_dict)
news_df

,Headers,Content,Read More
0,CMA CGM Senior Executives Visit the Port of Co...,"Mr Jesper Stenbak, Senior Vice President ADRO ...",https://www.slpa.lk/port-colombo-page/3e0042fd...
1,U.S. Assistant Secretary of State S. Paul Kapu...,The Sri Lanka Ports Authority welcomed S. Paul...,https://www.slpa.lk/port-colombo-page/433013b7...
2,SCO Delegation Visits Port of Colombo and Pilo...,The Secretary-General of the Shanghai Cooperat...,https://www.slpa.lk/port-colombo-page/9262e427...
3,Maersk Engages with SLPA on Enhancing Terminal...,Delegates from Maersk met with senior official...,https://www.slpa.lk/port-colombo-page/b4a63816...
4,SLPA Signs Terminal Service Agreement with Uni...,The Sri Lanka Ports Authority and Unifeeder La...,https://www.slpa.lk/port-colombo-page/803c048e...
...,...,...,...
976,More Passenger Vessels Calls at the Port of Co...,The number of passenger vessels calling at the...,https://www.slpa.lk/port-colombo-page/78a606e9...
977,President visits Japanese ŌĆśShip of the World...,President Maithripala Sirisena on Sunday visit...,https://www.slpa.lk/port-colombo-page/a7a275be...
978,PPP for port development,Sri Lanka Ports Authority (SLPA) is on the loo...,https://www.slpa.lk/port-colombo-page/35e80416...
979,For the first time in history the Port of Colo...,For the first time in history the Port of Colo...,https://www.slpa.lk/port-colombo-page/706d1003...
980,Herbilan Group launches second feeder service,Capitalizing on the success of Sri Lanka’s the...,https://www.slpa.lk/port-colombo-page/4b43f67b...

In [11]:
news_df.to_csv("slpa_news.csv",index=False)

Foreign Procuretment Details

In [12]:
import requests
from bs4 import BeautifulSoup

In [13]:
url="https://www.slpa.lk/port-colombo/foreign-purchases"
response= requests.get(url)
soup=BeautifulSoup(response.content,"lxml")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <!-- Mirrored from designarc.in/logis-cargo/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Mar 2016 02:46:54 GMT -->
 <head>
  <meta charset="utf-8"/>
  <title>
   Sri Lanka Ports Authority - Foreign-Purchases
  </title>
  <!-- viewport meta -->
  <link href="https://www.slpa.lk//favicon.ico" rel="icon" type="image/x-icon"/>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" name="viewport"/>
  <!--[if lte IE 9]>
    <h1 style="background-color: yellow; color: red;">You are using a version of IE less than IE9, Please Upgrade Browser</h1>
    <![endif]-->
  <script type="text/javascript">
   var js_base_url = "https://www.slpa.lk/";
        var js_site_url = "https://www.slpa.lk/";

        //alert(js_url_path);
  </script>
  <!-- Matomo -->
  <script>
   var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//mpma.slpa.lk/matomo/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
  </script>
  <!-- End Matomo Code -->
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-73651247-1', 'auto');
        ga('send', 'pageview');
  </script>
  <!-- styles -->
  <!-- helpers -->
  <!-- <link rel="stylesheet" href="application_resources/javascripts/plugins/bootstrap/css/bootstrap.min.css"> -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet"/>
  <!-- fontawesome css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
  <!-- strock gap icons -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/Stroke-Gap-Icons-Webfont/style.css" rel="stylesheet"/>
  <!-- revolution slider css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/revolution/css/settings.css" rel="stylesheet"/>
  <!-- flaticon css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/flaticon/flaticon.css" rel="stylesheet"/>
  <!-- jQuery ui css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet"/>
  <!-- owl carousel css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.carousel.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.theme.default.min.css" rel="stylesheet"/>
  <!-- animate css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/animate.min.css" rel="stylesheet"/>
  <!-- fancybox -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/fancyapps-fancyBox/source/jquery.fancybox.css" rel="stylesheet"/>
  <!-- master stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/style.css" rel="stylesheet"/>
  <!-- responsive stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/responsive.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/stylesheets/magnific-popup.css" rel="stylesheet" type="text/css"/>
  <!-- jQuery js -->
  <!-- <script src="application_resources/javascripts/plugins/jquery/jquery-1.11.3.min.js"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
  </script>
 </head>
 <body onload="xxx()">
  <script>
   function xxx(){
//alert("test");
}
  </script>
  <!-- Start header -->
  <header class="stricky" id="header">
   <div class="thm-container clearfix">
    <div class="logo pull-left">
     <a href="https://www.slpa.lk/">
      <img alt="" src="https://www.slpa.lk/application_resources/images/logo_1.png"/>
     </a>
    </div>
    <div class="header-info pull-right">
     <div class="info-box">
     </div>
     <div class="info-box">
      <div class="icon-box no-border">
       <i class="icon icon-FileBox">
       </i>
       <center>
        <a href="tel:1984">
         <img alt="" height="60" src="https://www.slpa.lk/application_resources/images/tel-1984.png"/>
        </a>
       </center>
      </div>
      <div class="text-box">
       <p class="highlighted">
        E-Mail : info@slpa.lk
       </p>
       <p>
        Fax : 	+94-11 2440651
       </p>
       <p class="highlighted">
        Call Us : +94-11 242 12 01
       </p>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=si&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Sinhala
       </a>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=ta&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Tamil
       </a>
      </div>
     </div>
     <div class="info-box search-box-wrapper">
      <br/>
      <div class="text-box">
      </div>
     </div>
    </div>
   </div>
  </header>
  <!-- End header  -->
  <!-- Start mainmenu -->
  <nav class="main-menu-wrapper stricky">
   <div class="thm-container menu-gradient">
    <div class="clearfix">
     <div class="nav-holder pull-left">
      <div class="nav-header">
       <button>
        <i class="fa fa-bars">
        </i>
       </button>
      </div>
      <div class="nav-footer">
       <ul class="nav notranslate">
        <li>
         <a href="https://www.slpa.lk/">
          Home
         </a>
        </li>
        <li class="has-submenu">
         <a>
          About
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/slpa">
            SLPA
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vision-and-mission">
            Vision &amp; Mission
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/board-of-directors">
            Board Of Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/act">
            ACT
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/procedures">
            Procedures
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/circulars">
            Circulars
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/awards">
            Awards
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/annual-reports">
            Annual Reports
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tariff">
            Tariff
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/right-to-information">
            Right To Information
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/publications">
            Publications
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Ports
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/colombo">
            Colombo
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/galle">
            Galle
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/trincomalee">
            Trincomalee
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/hip">
            HIP
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/oluvil">
            Oluvil
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/kankesanthurai">
            Kankesanthurai
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          E-Systems
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ber">
            Berthing Programme
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tms-esystem">
            TMS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/import">
            Import
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/export">
            Export
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/ro-ro">
            RO-RO
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/bulk-and-break-bulk">
            Bulk &amp; Break Bulk
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/fcl-cutoff-info">
            FCL Cutoff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/destuff-info">
            Destuff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/empty-containers">
            Empty Containers
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/online-entry-permits">
            Online Entry Permits
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vessels-in-port">
            Vessels In Port
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://hris.slpa.lk/login" target="_blank">
            HRIS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/clearing-passes">
            Clearing Passes
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/bungalow/index.php" target="_blank">
            Bungalow Booking
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://esys.slpa.lk/b/port-tours/" target="_blank">
            Port Tours
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Projects
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/projects">
            Projects
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Procurement
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/contacts-general-info">
            Contacts - General Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/foreign-purchases">
            Foreign-Purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/local-purchases">
            Local purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/other">
            Other
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Contacts
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ministry">
            Ministry
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/chairman-directors">
            Chairman &amp; Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/management-team">
            Management Team
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/mahapola">
            Mahapola Academy
           </a>

FOREIGN-PURCHASES->Electrical equipment

In [14]:
table = soup.find_all("tbody")[0]
print(table)

<tbody><tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr><tr><td width="20%">CES/FP/03/PT/6736 (EL)</td><td>01 No. 11/0.4KV, 600 KVA Cast Resin Dry Type Transformer</td><td style="text-align: center;">120,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3768837279.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/05/PT/6879 (EL)</td><td>Through Beam Sensor for Yard Automation at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6797154666.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/02/PT/6881 (EL)</td><td>Absolute Encoder for ARMG Cranes at ECT</td><td style="text-align: center;">30,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2731676665.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/03/PT/6886 (EL)</td><td>Brake Units for Gantry and Trolley Motors of ARMG Cranes at ECT</td><td style="text-align: center;">200,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6586278807.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/03/PT/6878 (EL)</td><td>100 Nos. Inductive Sensors for ARMG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3931574891.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/06/PT/6880 (EL)</td><td>03 Nos. Incremental Encoder for ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3521645166.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/03/PT/6882 (EL)</td><td>Magnetic Contractors and Spares for ARMG Cranes at ECT</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_506875477.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/05/PT/6883 (EL)</td><td>Small Circuit Breakers and Related Spares for ARMG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9209614205.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/06/PT/6888 (EL)</td><td>ABB PLC Spare Parts for ARMG Cranes at ECT</td><td style="text-align: center;">200,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9469868219.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/06/PT/6839 (EL)</td><td>01 No. 41M Trailing Cable for Alimak Elevators of JCT Stage V</td><td style="text-align: center;">80,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr><tr><td width="20%">CES/FP/05/PT/6891 (EL)</td><td>Brake Units for Cable Reel Motors of ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr><tr><td width="20%">CES/FP/03/PT/6890 (EL)</td><td>Circuit Breakers for AMRG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr><tr><td width="20%">CES/FP/06/PT/6892 (EL)</td><td>24C X 2.5 SQMM Festoon Cable for Cranes at JCT</td><td style="text-align: center;">75,000.00<br/></td><td>2026-09-29 10.00</td><td></td></tr><tr><td width="20%">CES/FP/02/PT/6889 (EL)</td><td>Shielded CAT6 Waterproof Cables for Encoders of ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-29 10.00</td><td></td></tr></tbody>

In [15]:
titles=table.find_all("strong")
titles

[<strong>Tender No.</strong>,
 <strong>Description</strong>,
 <strong>Bid Security Amount<br/>(Rs.)</strong>,
 <strong>Closing Date and Time</strong>,
 <strong>Attachment</strong>]

In [16]:
table_titles =[title.text for title in titles ]
table_titles

['Tender No.',
 'Description',
 'Bid Security Amount(Rs.)',
 'Closing Date and Time',
 'Attachment']

In [17]:
import pandas as pd

df=pd.DataFrame(columns=table_titles)
df

Empty DataFrame
Columns: [Tender No., Description, Bid Security Amount(Rs.), Closing Date and Time, Attachment]
Index: []

In [18]:
column_data = table.find_all("tr")
column_data

[<tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6736 (EL)</td><td>01 No. 11/0.4KV, 600 KVA Cast Resin Dry Type Transformer</td><td style="text-align: center;">120,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3768837279.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/05/PT/6879 (EL)</td><td>Through Beam Sensor for Yard Automation at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6797154666.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/02/PT/6881 (EL)</td><td>Absolute Encoder for ARMG Cranes at ECT</td><td style="text-align: center;">30,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2731676665.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6886 (EL)</td><td>Brake Units for Gantry and Trolley Motors of ARMG Cranes at ECT</td><td style="text-align: center;">200,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6586278807.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6878 (EL)</td><td>100 Nos. Inductive Sensors for ARMG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3931574891.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6880 (EL)</td><td>03 Nos. Incremental Encoder for ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3521645166.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6882 (EL)</td><td>Magnetic Contractors and Spares for ARMG Cranes at ECT</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_506875477.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/05/PT/6883 (EL)</td><td>Small Circuit Breakers and Related Spares for ARMG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9209614205.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6888 (EL)</td><td>ABB PLC Spare Parts for ARMG Cranes at ECT</td><td style="text-align: center;">200,000.00<br/></td><td>2026-09-03 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9469868219.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6839 (EL)</td><td>01 No. 41M Trailing Cable for Alimak Elevators of JCT Stage V</td><td style="text-align: center;">80,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr>,
 <tr><td width="20%">CES/FP/05/PT/6891 (EL)</td><td>Brake Units for Cable Reel Motors of ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6890 (EL)</td><td>Circuit Breakers for AMRG Cranes at ECT</td><td style="text-align: center;">60,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6892 (EL)</td><td>24C X 2.5 SQMM Festoon Cable for Cranes at JCT</td><td style="text-align: center;">75,000.00<br/></td><td>2026-09-29 10.00</td><td></td></tr>,
 <tr><td width="20%">CES/FP/02/PT/6889 (EL)</td><td>Shielded CAT6 Waterproof Cables for Encoders of ARMG Cranes at ECT</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-29 10.00</td><td></td></tr>]

In [19]:
for row in column_data:
    row_data=row.find_all("td")
    individual_row_data = [data.text.strip() for  data in row_data]
    print(individual_row_data)

    length= len(df)
    # identify the specific columns and rows
    df.loc[length]=individual_row_data

['Tender No.', 'Description', 'Bid Security Amount(Rs.)', 'Closing Date and Time', 'Attachment']
['CES/FP/03/PT/6736 (EL)', '01 No. 11/0.4KV, 600 KVA Cast Resin Dry Type Transformer', '120,000.00', '2026-09-01 10.00', 'download']
['CES/FP/05/PT/6879 (EL)', 'Through Beam Sensor for Yard Automation at ECT', '60,000.00', '2026-09-01 10.00', 'download']
['CES/FP/02/PT/6881 (EL)', 'Absolute Encoder for ARMG Cranes at ECT', '30,000.00', '2026-09-01 10.00', 'download']
['CES/FP/03/PT/6886 (EL)', 'Brake Units for Gantry and Trolley Motors of ARMG Cranes at ECT', '200,000.00', '2026-09-03 10.00', 'download']
['CES/FP/03/PT/6878 (EL)', '100 Nos. Inductive Sensors for ARMG Cranes at ECT', '60,000.00', '2026-09-03 10.00', 'download']
['CES/FP/06/PT/6880 (EL)', '03 Nos. Incremental Encoder for ARMG Cranes at ECT', '25,000.00', '2026-09-03 10.00', 'download']
['CES/FP/03/PT/6882 (EL)', 'Magnetic Contractors and Spares for ARMG Cranes at ECT', '50,000.00', '2026-09-03 10.00', 'download']
['CES/FP/05/PT/6883 (EL)', 'Small Circuit Breakers and Related Spares for ARMG Cranes at ECT', '60,000.00', '2026-09-03 10.00', 'download']
['CES/FP/06/PT/6888 (EL)', 'ABB PLC Spare Parts for ARMG Cranes at ECT', '200,000.00', '2026-09-03 10.00', 'download']
['CES/FP/06/PT/6839 (EL)', '01 No. 41M Trailing Cable for Alimak Elevators of JCT Stage V', '80,000.00', '2026-09-24 10.00', '']
['CES/FP/05/PT/6891 (EL)', 'Brake Units for Cable Reel Motors of ARMG Cranes at ECT', '25,000.00', '2026-09-24 10.00', '']
['CES/FP/03/PT/6890 (EL)', 'Circuit Breakers for AMRG Cranes at ECT', '60,000.00', '2026-09-24 10.00', '']
['CES/FP/06/PT/6892 (EL)', '24C X 2.5 SQMM Festoon Cable for Cranes at JCT', '75,000.00', '2026-09-29 10.00', '']
['CES/FP/02/PT/6889 (EL)', 'Shielded CAT6 Waterproof Cables for Encoders of ARMG Cranes at ECT', '25,000.00', '2026-09-29 10.00', '']

In [20]:
df[1:]

,Tender No.,Description,Bid Security Amount(Rs.),Closing Date and Time,Attachment
1,CES/FP/03/PT/6736 (EL),"01 No. 11/0.4KV, 600 KVA Cast Resin Dry Type T...","120,000.00",2026-09-01 10.00,download
2,CES/FP/05/PT/6879 (EL),Through Beam Sensor for Yard Automation at ECT,"60,000.00",2026-09-01 10.00,download
3,CES/FP/02/PT/6881 (EL),Absolute Encoder for ARMG Cranes at ECT,"30,000.00",2026-09-01 10.00,download
4,CES/FP/03/PT/6886 (EL),Brake Units for Gantry and Trolley Motors of A...,"200,000.00",2026-09-03 10.00,download
5,CES/FP/03/PT/6878 (EL),100 Nos. Inductive Sensors for ARMG Cranes at ECT,"60,000.00",2026-09-03 10.00,download
6,CES/FP/06/PT/6880 (EL),03 Nos. Incremental Encoder for ARMG Cranes at...,"25,000.00",2026-09-03 10.00,download
7,CES/FP/03/PT/6882 (EL),Magnetic Contractors and Spares for ARMG Crane...,"50,000.00",2026-09-03 10.00,download
8,CES/FP/05/PT/6883 (EL),Small Circuit Breakers and Related Spares for ...,"60,000.00",2026-09-03 10.00,download
9,CES/FP/06/PT/6888 (EL),ABB PLC Spare Parts for ARMG Cranes at ECT,"200,000.00",2026-09-03 10.00,download
10,CES/FP/06/PT/6839 (EL),01 No. 41M Trailing Cable for Alimak Elevators...,"80,000.00",2026-09-24 10.00,
11,CES/FP/05/PT/6891 (EL),Brake Units for Cable Reel Motors of ARMG Cran...,"25,000.00",2026-09-24 10.00,
12,CES/FP/03/PT/6890 (EL),Circuit Breakers for AMRG Cranes at ECT,"60,000.00",2026-09-24 10.00,
13,CES/FP/06/PT/6892 (EL),24C X 2.5 SQMM Festoon Cable for Cranes at JCT,"75,000.00",2026-09-29 10.00,
14,CES/FP/02/PT/6889 (EL),Shielded CAT6 Waterproof Cables for Encoders o...,"25,000.00",2026-09-29 10.00,

In [21]:
df[1:].to_csv("Foreing_Electrical_items_purchase.csv",index=False)

FOREIGN-PURCHASES -> Mechanical Equipment Table

In [22]:
table =soup.find_all("tbody")[1]
table

<tbody><tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr><tr><td width="20%">CES/FP/06/PT/6868 (MP)</td><td>04 Nos. of Grease Pumps for Stinis Single Lift Spreaders ARMG at ECT</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8427383759.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/06/PT/6856 (MP)</td><td>MLS 12 Plum Coupling with Spider Coupling (Plastic Insert) for the ARMG Cranes</td><td style="text-align: center;">23,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8150647464.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/02/PT/6869 (MAR)</td><td>Spares for Major Overhaul of Starboard Propulsion Unit (Aquamaster - US 3001/3600 CP) of Tug Gotaimbara)</td><td style="text-align: center;">1,500,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5926747075.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/04/PT/6829 (MP)</td><td>02 Nos. of 20 Ton Forklift</td><td style="text-align: center;">2,200,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3525041481.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/03/PT/6832 (MP)</td><td>02 Nos. of 15 Ton Forklift</td><td style="text-align: center;">1,100,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2240908234.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CES/FP/02/PT/6893 (MP)</td><td>01 No. of Electronic Control Module for Cummins QSX 15 Engine</td><td style="text-align: center;">30,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr></tbody>

In [23]:
table_titles= table.find_all("strong")
titles

[<strong>Tender No.</strong>,
 <strong>Description</strong>,
 <strong>Bid Security Amount<br/>(Rs.)</strong>,
 <strong>Closing Date and Time</strong>,
 <strong>Attachment</strong>]

In [24]:
table_titles=[title.text for title in titles]
table_titles

['Tender No.',
 'Description',
 'Bid Security Amount(Rs.)',
 'Closing Date and Time',
 'Attachment']

In [25]:
import pandas as pd

df1 =pd.DataFrame(columns=table_titles)
df1

Empty DataFrame
Columns: [Tender No., Description, Bid Security Amount(Rs.), Closing Date and Time, Attachment]
Index: []

In [26]:
column_data = table.find_all("tr")
column_data

[<tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6868 (MP)</td><td>04 Nos. of Grease Pumps for Stinis Single Lift Spreaders ARMG at ECT</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8427383759.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/06/PT/6856 (MP)</td><td>MLS 12 Plum Coupling with Spider Coupling (Plastic Insert) for the ARMG Cranes</td><td style="text-align: center;">23,000.00<br/></td><td>2026-09-01 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8150647464.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/02/PT/6869 (MAR)</td><td>Spares for Major Overhaul of Starboard Propulsion Unit (Aquamaster - US 3001/3600 CP) of Tug Gotaimbara)</td><td style="text-align: center;">1,500,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5926747075.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/04/PT/6829 (MP)</td><td>02 Nos. of 20 Ton Forklift</td><td style="text-align: center;">2,200,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3525041481.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/03/PT/6832 (MP)</td><td>02 Nos. of 15 Ton Forklift</td><td style="text-align: center;">1,100,000.00<br/></td><td>2026-09-10 10.00</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2240908234.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CES/FP/02/PT/6893 (MP)</td><td>01 No. of Electronic Control Module for Cummins QSX 15 Engine</td><td style="text-align: center;">30,000.00<br/></td><td>2026-09-24 10.00</td><td></td></tr>]

In [27]:
for row in column_data:
    row_data= row.find_all("td")
    individual_row_data = [data.text.strip() for data in row_data] 
    individual_row_data

    length = len(df1)
    df1.loc[length] = individual_row_data
    df1

In [28]:
df1[1:]

,Tender No.,Description,Bid Security Amount(Rs.),Closing Date and Time,Attachment
1,CES/FP/06/PT/6868 (MP),04 Nos. of Grease Pumps for Stinis Single Lift...,"50,000.00",2026-09-01 10.00,download
2,CES/FP/06/PT/6856 (MP),MLS 12 Plum Coupling with Spider Coupling (Pla...,"23,000.00",2026-09-01 10.00,download
3,CES/FP/02/PT/6869 (MAR),Spares for Major Overhaul of Starboard Propuls...,"1,500,000.00",2026-09-10 10.00,download
4,CES/FP/04/PT/6829 (MP),02 Nos. of 20 Ton Forklift,"2,200,000.00",2026-09-10 10.00,download
5,CES/FP/03/PT/6832 (MP),02 Nos. of 15 Ton Forklift,"1,100,000.00",2026-09-10 10.00,download
6,CES/FP/02/PT/6893 (MP),01 No. of Electronic Control Module for Cummin...,"30,000.00",2026-09-24 10.00,

In [29]:
df1[1:].to_csv("Foreing_Mechanical_items_purchase.csv")

LOCAL PURCHASES

In [30]:
url="https://www.slpa.lk/port-colombo/local-purchases"
response= requests.get(url)
soup=BeautifulSoup(response.content,"lxml")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <!-- Mirrored from designarc.in/logis-cargo/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Mar 2016 02:46:54 GMT -->
 <head>
  <meta charset="utf-8"/>
  <title>
   Sri Lanka Ports Authority - Local purchases
  </title>
  <!-- viewport meta -->
  <link href="https://www.slpa.lk//favicon.ico" rel="icon" type="image/x-icon"/>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" name="viewport"/>
  <!--[if lte IE 9]>
    <h1 style="background-color: yellow; color: red;">You are using a version of IE less than IE9, Please Upgrade Browser</h1>
    <![endif]-->
  <script type="text/javascript">
   var js_base_url = "https://www.slpa.lk/";
        var js_site_url = "https://www.slpa.lk/";

        //alert(js_url_path);
  </script>
  <!-- Matomo -->
  <script>
   var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//mpma.slpa.lk/matomo/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
  </script>
  <!-- End Matomo Code -->
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-73651247-1', 'auto');
        ga('send', 'pageview');
  </script>
  <!-- styles -->
  <!-- helpers -->
  <!-- <link rel="stylesheet" href="application_resources/javascripts/plugins/bootstrap/css/bootstrap.min.css"> -->
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet"/>
  <!-- fontawesome css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
  <!-- strock gap icons -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/Stroke-Gap-Icons-Webfont/style.css" rel="stylesheet"/>
  <!-- revolution slider css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/revolution/css/settings.css" rel="stylesheet"/>
  <!-- flaticon css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/flaticon/flaticon.css" rel="stylesheet"/>
  <!-- jQuery ui css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet"/>
  <!-- owl carousel css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.carousel.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/owl.carousel-2/assets/owl.theme.default.min.css" rel="stylesheet"/>
  <!-- animate css -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/animate.min.css" rel="stylesheet"/>
  <!-- fancybox -->
  <link href="https://www.slpa.lk/application_resources/javascripts/plugins/fancyapps-fancyBox/source/jquery.fancybox.css" rel="stylesheet"/>
  <!-- master stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/style.css" rel="stylesheet"/>
  <!-- responsive stylesheet -->
  <link href="https://www.slpa.lk/application_resources/stylesheets/responsive.css" rel="stylesheet"/>
  <link href="https://www.slpa.lk/application_resources/stylesheets/magnific-popup.css" rel="stylesheet" type="text/css"/>
  <!-- jQuery js -->
  <!-- <script src="application_resources/javascripts/plugins/jquery/jquery-1.11.3.min.js"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
  </script>
 </head>
 <body onload="xxx()">
  <script>
   function xxx(){
//alert("test");
}
  </script>
  <!-- Start header -->
  <header class="stricky" id="header">
   <div class="thm-container clearfix">
    <div class="logo pull-left">
     <a href="https://www.slpa.lk/">
      <img alt="" src="https://www.slpa.lk/application_resources/images/logo_1.png"/>
     </a>
    </div>
    <div class="header-info pull-right">
     <div class="info-box">
     </div>
     <div class="info-box">
      <div class="icon-box no-border">
       <i class="icon icon-FileBox">
       </i>
       <center>
        <a href="tel:1984">
         <img alt="" height="60" src="https://www.slpa.lk/application_resources/images/tel-1984.png"/>
        </a>
       </center>
      </div>
      <div class="text-box">
       <p class="highlighted">
        E-Mail : info@slpa.lk
       </p>
       <p>
        Fax : 	+94-11 2440651
       </p>
       <p class="highlighted">
        Call Us : +94-11 242 12 01
       </p>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=si&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Sinhala
       </a>
       <a class="btn btn-xs btn-info" href="https://www-slpa-lk.translate.goog/?_x_tr_sl=auto&amp;_x_tr_tl=ta&amp;_x_tr_hl=en&amp;_x_tr_pto=wapp" target="_blank">
        Tamil
       </a>
      </div>
     </div>
     <div class="info-box search-box-wrapper">
      <br/>
      <div class="text-box">
      </div>
     </div>
    </div>
   </div>
  </header>
  <!-- End header  -->
  <!-- Start mainmenu -->
  <nav class="main-menu-wrapper stricky">
   <div class="thm-container menu-gradient">
    <div class="clearfix">
     <div class="nav-holder pull-left">
      <div class="nav-header">
       <button>
        <i class="fa fa-bars">
        </i>
       </button>
      </div>
      <div class="nav-footer">
       <ul class="nav notranslate">
        <li>
         <a href="https://www.slpa.lk/">
          Home
         </a>
        </li>
        <li class="has-submenu">
         <a>
          About
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/slpa">
            SLPA
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vision-and-mission">
            Vision &amp; Mission
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/board-of-directors">
            Board Of Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/act">
            ACT
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/procedures">
            Procedures
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/circulars">
            Circulars
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/awards">
            Awards
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/annual-reports">
            Annual Reports
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tariff">
            Tariff
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/right-to-information">
            Right To Information
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/publications">
            Publications
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Ports
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/colombo">
            Colombo
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/galle">
            Galle
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/trincomalee">
            Trincomalee
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/hip">
            HIP
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/oluvil">
            Oluvil
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/kankesanthurai">
            Kankesanthurai
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          E-Systems
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ber">
            Berthing Programme
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/tms-esystem">
            TMS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/import">
            Import
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/export">
            Export
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/ro-ro">
            RO-RO
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/bulk-and-break-bulk">
            Bulk &amp; Break Bulk
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/fcl-cutoff-info">
            FCL Cutoff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/destuff-info">
            Destuff Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/empty-containers">
            Empty Containers
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/online-entry-permits">
            Online Entry Permits
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/vessels-in-port">
            Vessels In Port
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://hris.slpa.lk/login" target="_blank">
            HRIS
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/clearing-passes">
            Clearing Passes
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/bungalow/index.php" target="_blank">
            Bungalow Booking
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://esys.slpa.lk/b/port-tours/" target="_blank">
            Port Tours
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Projects
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/projects">
            Projects
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Procurement
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/contacts-general-info">
            Contacts - General Info
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/foreign-purchases">
            Foreign-Purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/local-purchases">
            Local purchases
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo-list/other">
            Other
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
         </ul>
        </li>
        <li class="has-submenu">
         <a>
          Contacts
         </a>
         <ul class="submenu">
          <li>
           <a href="https://www.slpa.lk/port-colombo/ministry">
            Ministry
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/chairman-directors">
            Chairman &amp; Directors
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/management-team">
            Management Team
           </a>
           <!-- <ul class="submenu">                                                                     <li><a href=''></a> </li>



                                   </ul>-->
          </li>
          <li>
           <a href="https://www.slpa.lk/port-colombo/mahapola">
            Mahapola Academy
           </a>

LOCAL PURCHASES->Electrical Equipment

In [31]:
table=soup.find_all("tbody")[0]
table

<tbody><tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr><tr><td width="20%">CMS/LP/26/SQ/03/137</td><td>POWER SUPPLY UNIT
</td><td style="text-align: center;"><br/></td><td>2026-08-25 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6676549613.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/18/139</td><td>Voltage Regulator, for Main/Aux. Gen.
</td><td style="text-align: center;"><br/></td><td>2026-08-25 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7150644487.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/06/149</td><td>CAPACITORS 2.5uF, 400V
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7365409410.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/10/137</td><td>SEALED TYPE BATTERY 12V 90 AMPH (SEMI - MAINT. FREE)
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4747167541.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/17/103</td><td>MAIN DISTRIBUTION BOARD 100A , OUTDOOR
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_460561634.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/14/082 </td><td>MCCB 4 P, 60A WITH THERM. &amp; MAG. TRIPPING
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_35186703.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/08/170</td><td>ELECTRICAL ITEMS
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1855959598.pdf"><i class="fa fa-download"></i> download</a></td></tr></tbody>

In [32]:
table_titles=table.find_all("strong")
table_titles

[<strong>Tender No.</strong>,
 <strong>Description</strong>,
 <strong>Bid Security Amount<br/>(Rs.)</strong>,
 <strong>Closing Date and Time</strong>,
 <strong>Attachment</strong>]

In [33]:
table_titles=[titles.text for titles in table_titles]
table_titles

['Tender No.',
 'Description',
 'Bid Security Amount(Rs.)',
 'Closing Date and Time',
 'Attachment']

In [34]:
import pandas as pd

df=pd.DataFrame(columns=table_titles)
df

Empty DataFrame
Columns: [Tender No., Description, Bid Security Amount(Rs.), Closing Date and Time, Attachment]
Index: []

In [35]:
column_data=table.find_all("tr")
column_data

[<tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/03/137</td><td>POWER SUPPLY UNIT
 </td><td style="text-align: center;"><br/></td><td>2026-08-25 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6676549613.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/18/139</td><td>Voltage Regulator, for Main/Aux. Gen.
 </td><td style="text-align: center;"><br/></td><td>2026-08-25 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7150644487.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/06/149</td><td>CAPACITORS 2.5uF, 400V
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7365409410.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/10/137</td><td>SEALED TYPE BATTERY 12V 90 AMPH (SEMI - MAINT. FREE)
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4747167541.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/17/103</td><td>MAIN DISTRIBUTION BOARD 100A , OUTDOOR
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_460561634.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/14/082 </td><td>MCCB 4 P, 60A WITH THERM. &amp; MAG. TRIPPING
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_35186703.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/08/170</td><td>ELECTRICAL ITEMS
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1855959598.pdf"><i class="fa fa-download"></i> download</a></td></tr>]

In [36]:
for row in column_data:
    row_data= row.find_all("td")
    each_row_data = [data.text.strip() for data in row_data] 
    each_row_data

    length = len(df)
    df.loc[length] = each_row_data
    df

In [37]:
df[1:]

,Tender No.,Description,Bid Security Amount(Rs.),Closing Date and Time,Attachment
1,CMS/LP/26/SQ/03/137,POWER SUPPLY UNIT,,2026-08-25 13.30,download
2,CMS/LP/26/SQ/18/139,"Voltage Regulator, for Main/Aux. Gen.",,2026-08-25 13.30,download
3,CMS/LP/26/SQ/06/149,"CAPACITORS 2.5uF, 400V",,2026-08-28 13.30,download
4,CMS/LP/26/SQ/10/137,SEALED TYPE BATTERY 12V 90 AMPH (SEMI - MAINT....,,2026-08-28 13.30,download
5,CMS/LP/26/SQ/17/103,"MAIN DISTRIBUTION BOARD 100A , OUTDOOR",,2026-08-31 13.30,download
6,CMS/LP/26/SQ/14/082,"MCCB 4 P, 60A WITH THERM. & MAG. TRIPPING",,2026-08-31 13.30,download
7,CMS/LP/26/SQ/08/170,ELECTRICAL ITEMS,,2026-08-31 13.30,download

In [38]:
df[1:].to_csv("Local_Electrical_items_purchases.csv",index=False)

LOCAL PURCHASES->Mechanical Equipment

In [39]:
table=soup.find_all("tbody")[1] #get mechanical equipment
table

<tbody><tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr><tr><td width="20%">CMS/LP/26/SQ/04/141</td><td>ALTERNATOR ASSY. FOR NISSAN UD LORRY
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5200411938.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/04/140</td><td>POWER STEERING BOX ASSY
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2560122837.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/10/025</td><td>Supply &amp; Installation of 36000 Wall Mounted Non Inverter Type Air Conditioners
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4393291063.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/14/123 </td><td>MOTOR TYRES 700 R15, 10PLY
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6925549092.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/01/138</td><td>Spares for Sea Water Pump
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6180510716.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/14/108</td><td>MOTOR TUBES 12.5X80-18 SN
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7074965653.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/16/129</td><td>ROTARY TYPE AC COMPRESSOR 24000 BTU/HR, R-32, 230V, 50 HZ
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1312091154.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/25/SQ/03/140</td><td>TIE ROD END SET
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9587888354.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/05/140</td><td>COMPRESSOR LEADS THREE WIRE SET WITH CLIPS
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_790211702.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/06/153</td><td>Front Panel Display PCB Complete Flex &amp; Plastic Case HYT TM-610
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6812347038.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/PT/14/012</td><td>30 Nos. Forelock Shackle (80 Ton, Dia 50MM)</td><td style="text-align: center;">40,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/03/056</td><td>Spares for Gear Reducers of Anti-Sway System - ZPMC 41T RTG Cranes</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/16/059</td><td>Spare Parts for Tadano TR - 100M -1 Mobile Crane</td><td style="text-align: center;">70,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/05/059</td><td>Spares for Konecranes TFC 45HC Reach Stackers</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/SQ/01/140 </td><td>Spares for Main Engines Wartsila Suranimala
</td><td style="text-align: center;"><br/></td><td>2026-09-01 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3147096219.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/PT/07/055</td><td>Refurbishment of Safety Devices Fitted in Alimak Elevators in STS Cranes</td><td style="text-align: center;">165,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/05/058</td><td>Spares for Kato NK 250 E - III 25 Ton Mobile Crane</td><td style="text-align: center;">45,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/05/057</td><td>Safety Devices of Alimak Elevators Fitted to J-7 and J-8 STS Cranes</td><td style="text-align: center;">83,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/06/054</td><td>Spare Parts for Hyster RS45 Reach Stacker</td><td style="text-align: center;">35,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/18/055</td><td>Spare Parts for Terberg Yard Tractors</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/01/062</td><td>Spare Parts for the UD Nissan prime Movers</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/14/056</td><td>24 Nos. Motor Tyres 21.00X25 40 PLY Tubeless</td><td style="text-align: center;">216,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/18/054</td><td>05 Nos. Cushion &amp; Back Assy for UD Nissan Prime Movers</td><td style="text-align: center;">19,500.00<br/></td><td>2026-09-03 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/PT/16/060</td><td>Spares for Terex FDC-500 Top Lift Truck</td><td style="text-align: center;">100,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr><tr><td width="20%">CMS/LP/26/SQ/04/142</td><td>WIRE ROPE LUBRICANT (FLUID)
</td><td style="text-align: center;"><br/></td><td>2026-09-03 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6690947390.pdf"><i class="fa fa-download"></i> download</a></td></tr></tbody>

In [40]:
table_titles=table.find_all("strong")
table_titles

[<strong>Tender No.</strong>,
 <strong>Description</strong>,
 <strong>Bid Security Amount<br/>(Rs.)</strong>,
 <strong>Closing Date and Time</strong>,
 <strong>Attachment</strong>]

In [41]:
table_titles=[title.text for title in table_titles]
table_titles

['Tender No.',
 'Description',
 'Bid Security Amount(Rs.)',
 'Closing Date and Time',
 'Attachment']

In [42]:
import pandas as pd
df1=pd.DataFrame(columns=table_titles)
df1

Empty DataFrame
Columns: [Tender No., Description, Bid Security Amount(Rs.), Closing Date and Time, Attachment]
Index: []

In [43]:
column_data=table.find_all("tr")
column_data

[<tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/04/141</td><td>ALTERNATOR ASSY. FOR NISSAN UD LORRY
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5200411938.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/04/140</td><td>POWER STEERING BOX ASSY
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2560122837.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/10/025</td><td>Supply &amp; Installation of 36000 Wall Mounted Non Inverter Type Air Conditioners
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4393291063.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/14/123 </td><td>MOTOR TYRES 700 R15, 10PLY
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6925549092.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/01/138</td><td>Spares for Sea Water Pump
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6180510716.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/14/108</td><td>MOTOR TUBES 12.5X80-18 SN
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_7074965653.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/16/129</td><td>ROTARY TYPE AC COMPRESSOR 24000 BTU/HR, R-32, 230V, 50 HZ
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1312091154.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/25/SQ/03/140</td><td>TIE ROD END SET
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9587888354.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/05/140</td><td>COMPRESSOR LEADS THREE WIRE SET WITH CLIPS
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_790211702.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/06/153</td><td>Front Panel Display PCB Complete Flex &amp; Plastic Case HYT TM-610
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6812347038.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/14/012</td><td>30 Nos. Forelock Shackle (80 Ton, Dia 50MM)</td><td style="text-align: center;">40,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/03/056</td><td>Spares for Gear Reducers of Anti-Sway System - ZPMC 41T RTG Cranes</td><td style="text-align: center;">50,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/16/059</td><td>Spare Parts for Tadano TR - 100M -1 Mobile Crane</td><td style="text-align: center;">70,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/05/059</td><td>Spares for Konecranes TFC 45HC Reach Stackers</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-01 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/01/140 </td><td>Spares for Main Engines Wartsila Suranimala
 </td><td style="text-align: center;"><br/></td><td>2026-09-01 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_3147096219.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/07/055</td><td>Refurbishment of Safety Devices Fitted in Alimak Elevators in STS Cranes</td><td style="text-align: center;">165,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/05/058</td><td>Spares for Kato NK 250 E - III 25 Ton Mobile Crane</td><td style="text-align: center;">45,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/05/057</td><td>Safety Devices of Alimak Elevators Fitted to J-7 and J-8 STS Cranes</td><td style="text-align: center;">83,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/06/054</td><td>Spare Parts for Hyster RS45 Reach Stacker</td><td style="text-align: center;">35,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/18/055</td><td>Spare Parts for Terberg Yard Tractors</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-02 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/01/062</td><td>Spare Parts for the UD Nissan prime Movers</td><td style="text-align: center;">25,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/14/056</td><td>24 Nos. Motor Tyres 21.00X25 40 PLY Tubeless</td><td style="text-align: center;">216,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/18/054</td><td>05 Nos. Cushion &amp; Back Assy for UD Nissan Prime Movers</td><td style="text-align: center;">19,500.00<br/></td><td>2026-09-03 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/16/060</td><td>Spares for Terex FDC-500 Top Lift Truck</td><td style="text-align: center;">100,000.00<br/></td><td>2026-09-03 13.30</td><td></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/04/142</td><td>WIRE ROPE LUBRICANT (FLUID)
 </td><td style="text-align: center;"><br/></td><td>2026-09-03 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6690947390.pdf"><i class="fa fa-download"></i> download</a></td></tr>]

In [44]:
for row in column_data:
    row_data=row.find_all("td")
    each_row_data=[data.text.strip() for data in row_data]
    each_row_data

    length=len(df1)
    df1.loc[length]=each_row_data
    df1

In [45]:
df1[1:] #print from index 1 to all

,Tender No.,Description,Bid Security Amount(Rs.),Closing Date and Time,Attachment
1,CMS/LP/26/SQ/04/141,ALTERNATOR ASSY. FOR NISSAN UD LORRY,,2026-08-28 13.30,download
2,CMS/LP/26/SQ/04/140,POWER STEERING BOX ASSY,,2026-08-28 13.30,download
3,CMS/LP/26/SQ/10/025,Supply & Installation of 36000 Wall Mounted No...,,2026-08-28 13.30,download
4,CMS/LP/26/SQ/14/123,"MOTOR TYRES 700 R15, 10PLY",,2026-08-28 13.30,download
5,CMS/LP/26/SQ/01/138,Spares for Sea Water Pump,,2026-08-31 13.30,download
6,CMS/LP/26/SQ/14/108,MOTOR TUBES 12.5X80-18 SN,,2026-08-31 13.30,download
7,CMS/LP/26/SQ/16/129,"ROTARY TYPE AC COMPRESSOR 24000 BTU/HR, R-32, ...",,2026-08-31 13.30,download
8,CMS/LP/25/SQ/03/140,TIE ROD END SET,,2026-08-31 13.30,download
9,CMS/LP/26/SQ/05/140,COMPRESSOR LEADS THREE WIRE SET WITH CLIPS,,2026-08-31 13.30,download
10,CMS/LP/26/SQ/06/153,Front Panel Display PCB Complete Flex & Plasti...,,2026-08-31 13.30,download
11,CMS/LP/26/PT/14/012,"30 Nos. Forelock Shackle (80 Ton, Dia 50MM)","40,000.00",2026-09-01 13.30,
12,CMS/LP/26/PT/03/056,Spares for Gear Reducers of Anti-Sway System -...,"50,000.00",2026-09-01 13.30,
13,CMS/LP/26/PT/16/059,Spare Parts for Tadano TR - 100M -1 Mobile Crane,"70,000.00",2026-09-01 13.30,
14,CMS/LP/26/PT/05/059,Spares for Konecranes TFC 45HC Reach Stackers,"25,000.00",2026-09-01 13.30,
15,CMS/LP/26/SQ/01/140,Spares for Main Engines Wartsila Suranimala,,2026-09-01 13.30,download
16,CMS/LP/26/PT/07/055,Refurbishment of Safety Devices Fitted in Alim...,"165,000.00",2026-09-02 13.30,
17,CMS/LP/26/PT/05/058,Spares for Kato NK 250 E - III 25 Ton Mobile C...,"45,000.00",2026-09-02 13.30,
18,CMS/LP/26/PT/05/057,Safety Devices of Alimak Elevators Fitted to J...,"83,000.00",2026-09-02 13.30,
19,CMS/LP/26/PT/06/054,Spare Parts for Hyster RS45 Reach Stacker,"35,000.00",2026-09-02 13.30,
20,CMS/LP/26/PT/18/055,Spare Parts for Terberg Yard Tractors,"25,000.00",2026-09-02 13.30,
21,CMS/LP/26/PT/01/062,Spare Parts for the UD Nissan prime Movers,"25,000.00",2026-09-03 13.30,
22,CMS/LP/26/PT/14/056,24 Nos. Motor Tyres 21.00X25 40 PLY Tubeless,"216,000.00",2026-09-03 13.30,
23,CMS/LP/26/PT/18/054,05 Nos. Cushion & Back Assy for UD Nissan Prim...,"19,500.00",2026-09-03 13.30,
24,CMS/LP/26/PT/16/060,Spares for Terex FDC-500 Top Lift Truck,"100,000.00",2026-09-03 13.30,
25,CMS/LP/26/SQ/04/142,WIRE ROPE LUBRICANT (FLUID),,2026-09-03 13.30,download

In [46]:
df1[1:].to_csv("Local_Machanical_items_Purchases.csv",index=False) #import the table as csv file

LOCAL PURCHASES->Other Materials & Equipment

In [47]:
table=soup.find_all("tbody")[2] #get third one table 
table

<tbody><tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr><tr><td width="20%">CMS/LP/26/SQ/10/109</td><td>RENEWAL OF PROFESSIONAL VIDEO CONFERENCE SOLUTION - ZOOM PRO VIDEO
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8093097442.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/173 </td><td>TUMBLER GLASSES 3/4 PINT
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_53933109.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/173</td><td>TUMBLER GLASSES 3/4 PINT
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_129930088.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/170</td><td>GARBAGE BAG 48" X36" 100 Bags Per Pkt
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4162649884.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/172</td><td>PVC CABLE,SWITCHES TUMBLER,SUNK BOXES
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5491701383.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/171</td><td>PVC CABLE SINGLE CORE 1/1.13mm (1/044") (100M ROLL)
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9969592755.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/06/150</td><td>REGULATORS FOR CEILING FAN
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5137636750.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/25/FQ/01/157 </td><td>ASPHALT CONCRETE WEARING COARSE WITHOUT TRANSPORT
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1439961809.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/03/141</td><td>UMBRELLA GENT, DOUBLE RIB
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1614266433.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/18/020</td><td>Ready Mixed Concrete 30G
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1982611860.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/08/169</td><td>Weed Killer (4 Ltr Can)
</td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9438393898.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/03/101</td><td>SURGICAL MASK
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1063504545.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/03/101</td><td>SURGICAL MASK
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4359413255.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/05/141</td><td>BED SHEETS 90" X 54"
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6738883801.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/19/007</td><td>Iron Racking System
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_510100522.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/25/SQ/04/195</td><td>GLOVES LEATHER (FOR GENERAL USE)
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6255628927.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/10/138</td><td>REFRIGERANT GAS R32 10kg CYLINDER
</td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2189050181.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/SQ/17/156</td><td>TEMPORARY PERMITS
</td><td style="text-align: center;"><br/></td><td>2026-09-02 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2462347750.pdf"><i class="fa fa-download"></i> download</a></td></tr><tr><td width="20%">CMS/LP/26/PT/09/176(KC)</td><td>65,000kg of Fish</td><td style="text-align: center;">1,100,000.00<br/></td><td>2026-09-17 13.30</td><td></td></tr></tbody>

In [48]:
table_titles=table.find_all("strong")
table_titles

[<strong>Tender No.</strong>,
 <strong>Description</strong>,
 <strong>Bid Security Amount<br/>(Rs.)</strong>,
 <strong>Closing Date and Time</strong>,
 <strong>Attachment</strong>]

In [49]:
table_titles=[title.text for title in table_titles]
table_titles

['Tender No.',
 'Description',
 'Bid Security Amount(Rs.)',
 'Closing Date and Time',
 'Attachment']

In [50]:
import pandas as pd
df3=pd.DataFrame(columns=table_titles)
df3

Empty DataFrame
Columns: [Tender No., Description, Bid Security Amount(Rs.), Closing Date and Time, Attachment]
Index: []

In [51]:
column_data=table.find_all("tr")
column_data

[<tr><td width="30%"><strong>Tender No.</strong></td><td><strong>Description</strong></td><td style="text-align: center;"><strong>Bid Security Amount<br/>(Rs.)</strong></td><td><strong>Closing Date and Time</strong></td><td><strong>Attachment</strong></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/10/109</td><td>RENEWAL OF PROFESSIONAL VIDEO CONFERENCE SOLUTION - ZOOM PRO VIDEO
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_8093097442.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/173 </td><td>TUMBLER GLASSES 3/4 PINT
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_53933109.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/173</td><td>TUMBLER GLASSES 3/4 PINT
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_129930088.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/170</td><td>GARBAGE BAG 48" X36" 100 Bags Per Pkt
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4162649884.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/172</td><td>PVC CABLE,SWITCHES TUMBLER,SUNK BOXES
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5491701383.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/171</td><td>PVC CABLE SINGLE CORE 1/1.13mm (1/044") (100M ROLL)
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9969592755.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/06/150</td><td>REGULATORS FOR CEILING FAN
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_5137636750.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/25/FQ/01/157 </td><td>ASPHALT CONCRETE WEARING COARSE WITHOUT TRANSPORT
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1439961809.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/03/141</td><td>UMBRELLA GENT, DOUBLE RIB
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1614266433.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/18/020</td><td>Ready Mixed Concrete 30G
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1982611860.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/08/169</td><td>Weed Killer (4 Ltr Can)
 </td><td style="text-align: center;"><br/></td><td>2026-08-28 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_9438393898.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/03/101</td><td>SURGICAL MASK
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_1063504545.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/03/101</td><td>SURGICAL MASK
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_4359413255.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/05/141</td><td>BED SHEETS 90" X 54"
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6738883801.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/19/007</td><td>Iron Racking System
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_510100522.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/25/SQ/04/195</td><td>GLOVES LEATHER (FOR GENERAL USE)
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_6255628927.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/10/138</td><td>REFRIGERANT GAS R32 10kg CYLINDER
 </td><td style="text-align: center;"><br/></td><td>2026-08-31 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2189050181.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/SQ/17/156</td><td>TEMPORARY PERMITS
 </td><td style="text-align: center;"><br/></td><td>2026-09-02 13.30</td><td><a download="" href="https://www.slpa.lk//uploads/article/tender_assets/tender_2462347750.pdf"><i class="fa fa-download"></i> download</a></td></tr>,
 <tr><td width="20%">CMS/LP/26/PT/09/176(KC)</td><td>65,000kg of Fish</td><td style="text-align: center;">1,100,000.00<br/></td><td>2026-09-17 13.30</td><td></td></tr>]

In [52]:
for row in column_data:
    row_data=row.find_all("td")
    each_row_data=[data.text.strip() for data in row_data]
    each_row_data

    length=len(df3)
    df3.loc[length]=each_row_data
    df3

In [53]:
df3[1:]

,Tender No.,Description,Bid Security Amount(Rs.),Closing Date and Time,Attachment
1,CMS/LP/26/SQ/10/109,RENEWAL OF PROFESSIONAL VIDEO CONFERENCE SOLUT...,,2026-08-28 13.30,download
2,CMS/LP/26/SQ/19/173,TUMBLER GLASSES 3/4 PINT,,2026-08-28 13.30,download
3,CMS/LP/26/SQ/19/173,TUMBLER GLASSES 3/4 PINT,,2026-08-28 13.30,download
4,CMS/LP/26/SQ/19/170,"GARBAGE BAG 48"" X36"" 100 Bags Per Pkt",,2026-08-28 13.30,download
5,CMS/LP/26/SQ/19/172,"PVC CABLE,SWITCHES TUMBLER,SUNK BOXES",,2026-08-28 13.30,download
6,CMS/LP/26/SQ/19/171,"PVC CABLE SINGLE CORE 1/1.13mm (1/044"") (100M ...",,2026-08-28 13.30,download
7,CMS/LP/26/SQ/06/150,REGULATORS FOR CEILING FAN,,2026-08-28 13.30,download
8,CMS/LP/25/FQ/01/157,ASPHALT CONCRETE WEARING COARSE WITHOUT TRANSPORT,,2026-08-28 13.30,download
9,CMS/LP/26/SQ/03/141,"UMBRELLA GENT, DOUBLE RIB",,2026-08-28 13.30,download
10,CMS/LP/26/SQ/18/020,Ready Mixed Concrete 30G,,2026-08-28 13.30,download
11,CMS/LP/26/SQ/08/169,Weed Killer (4 Ltr Can),,2026-08-28 13.30,download
12,CMS/LP/26/SQ/03/101,SURGICAL MASK,,2026-08-31 13.30,download
13,CMS/LP/26/SQ/03/101,SURGICAL MASK,,2026-08-31 13.30,download
14,CMS/LP/26/SQ/05/141,"BED SHEETS 90"" X 54""",,2026-08-31 13.30,download
15,CMS/LP/26/SQ/19/007,Iron Racking System,,2026-08-31 13.30,download
16,CMS/LP/25/SQ/04/195,GLOVES LEATHER (FOR GENERAL USE),,2026-08-31 13.30,download
17,CMS/LP/26/SQ/10/138,REFRIGERANT GAS R32 10kg CYLINDER,,2026-08-31 13.30,download
18,CMS/LP/26/SQ/17/156,TEMPORARY PERMITS,,2026-09-02 13.30,download
19,CMS/LP/26/PT/09/176(KC),"65,000kg of Fish","1,100,000.00",2026-09-17 13.30,

In [54]:
df3[1:].to_csv("Local_Other_Material_&_Equipment_Purchases.csv",index=False)

2024 Annual Report

In [ ]:
import pdfplumber
import pandas as pd

with pdfplumber.open('annual-report-2024.pdf') as pdf:

    page = pdf.pages[9]

    table_settings ={
        "vertical_strategy":"text",
        "horizontal_strategy":"text",
    }

    tables = page.extract_tables(table_settings)

    for i,tables in enumerate(tables):
        df=pd.DataFrame(tables)
        print(df.)

                  0  1         2             3      4
0       Description         2023  2024 Varianc  e (%)
1
2   Port of Colombo        4,237         3,968   -6.3
3
4     Port of Galle           23             6  -73.9
..              ... ..       ...           ...    ...
62    Transshipment  5  ,754,247     6,315,195    9.7
63
64       Re-stowing      205,659       307,619   49.6
65
66            Total  6  ,949,912     7,792,069   12.1

[67 rows x 5 columns]